import type { SFSymbol } from "expo-symbols";

/**
 * SF Symbols compatibles iOS 15+ (deploymentTarget 15.1).
 * Éviter book.pages.fill, list.number, books.vertical.fill (souvent iOS 16/17+).
 */
const IOS_UNSAFE_SF = new Set<string>([
  "book.pages.fill",
  "list.number",
  "books.vertical.fill",
  "hands.and.sparkles.fill",
  "person.badge.plus",
]);

/** Correspondances MaterialCommunityIcons → SF Symbol (iOS). */
export const MCI_TO_SF = {
  account: "person.crop.circle",
  "account-check": "person.crop.circle.badge.checkmark",
  "account-circle": "person.crop.circle",
  "account-cog": "gear",
  "account-edit": "pencil",
  "account-heart": "heart.circle.fill",
  "account-multiple": "person.2.fill",
  "account-plus": "person.crop.circle.badge.plus",
  alert: "exclamationmark.triangle.fill",
  "alert-circle": "exclamationmark.circle.fill",
  "arrow-left": "arrow.left",
  "arrow-right": "arrow.right",
  "backup-restore": "arrow.clockwise.circle",
  bell: "bell.fill",
  "bell-outline": "bell",
  "bell-ring": "bell.badge.fill",
  "bell-ring-outline": "bell",
  book: "book.fill",
  "book-multiple": "books.vertical",
  "book-open-page-variant": "book.fill",
  "book-outline": "book.closed.fill",
  bookshelf: "books.vertical",
  "book-open-variant": "book.fill",
  broom: "paintbrush.fill",
  bug: "ladybug",
  "bug-outline": "ladybug",
  "calendar-week": "calendar",
  "chart-bar": "chart.bar.fill",
  "chart-line": "chart.line.uptrend.xyaxis",
  "chart-timeline-variant": "chart.xyaxis.line",
  calendar: "calendar",
  "calendar-heart": "calendar",
  compass: "location.north.circle.fill",
  "compass-outline": "location.north.line.fill",
  counter: "circle.grid.3x3.fill",
  check: "checkmark",
  "check-circle": "checkmark.circle.fill",
  circle: "circle",
  "circle-outline": "circle",
  "chevron-down": "chevron.down",
  "chevron-right": "chevron.right",
  "chevron-up": "chevron.up",
  city: "building.2",
  "clock-outline": "clock",
  "clock-time-four": "clock.fill",
  close: "xmark",
  "close-circle": "xmark.circle.fill",
  "cloud-download": "icloud.and.arrow.down",
  "cloud-upload": "icloud.and.arrow.up",
  cog: "gear",
  "cog-outline": "gearshape",
  "credit-card": "creditcard",
  "crosshairs-gps": "location.viewfinder",
  crown: "crown",
  database: "cylinder.split.1x2",
  "dots-grid": "square.grid.2x2.fill",
  delete: "trash",
  "delete-forever": "trash.slash",
  "delete-outline": "trash.circle",
  "delete-sweep": "trash.fill",
  directions: "arrow.triangle.turn.up.right.circle.fill",
  download: "arrow.down.circle",
  "download-multiple": "arrow.down.doc",
  "download-outline": "arrow.down.circle",
  email: "envelope",
  "email-outline": "envelope",
  eye: "eye.fill",
  "eye-off": "eye.slash",
  gesture: "hand.draw",
  "gesture-swipe-horizontal": "hand.draw",
  "hand-heart": "hands.clap",
  "human-handsup": "hand.raised.fill",
  heart: "heart.fill",
  "heart-multiple": "heart.fill",
  "heart-outline": "heart",
  home: "house.fill",
  help: "questionmark.circle.fill",
  "help-circle": "questionmark.circle",
  "format-list-numbered": "list.bullet",
  information: "info.circle",
  "information-outline": "info.circle",
  key: "key",
  loading: "arrow.clockwise",
  lock: "lock.fill",
  "lock-check": "lock.fill",
  "lock-plus": "plus.circle.fill",
  login: "arrow.right.square.fill",
  logout: "rectangle.portrait.and.arrow.right",
  "map-marker": "mappin.circle.fill",
  "map-marker-outline": "mappin",
  "map-marker-radius": "mappin.circle",
  mosque: "building.columns.fill",
  music: "music.note",
  "music-circle": "music.note.circle.fill",
  "note-text": "note.text",
  pause: "pause.fill",
  pencil: "pencil",
  palette: "paintpalette",
  "pause-circle": "pause.circle",
  "pencil-outline": "pencil",
  phone: "phone",
  play: "play.fill",
  "play-circle": "play.circle",
  refresh: "arrow.clockwise",
  school: "building.columns.fill",
  "share-variant": "square.and.arrow.up",
  "shield-account": "shield.lefthalf.fill",
  "shield-check": "checkmark.shield.fill",
  "skip-next": "forward.end",
  "skip-previous": "backward.end",
  "star-circle": "star.circle",
  "star-crescent": "moon.stars.fill",
  "star-outline": "star",
  sun: "sun.max.fill",
  stop: "stop.fill",
  "volume-high": "speaker.wave.3.fill",
  "volume-off": "speaker.slash.fill",
  water: "drop.fill",
  "theme-light-dark": "circle.lefthalf.filled",
  translate: "globe",
  trophy: "trophy",
  "two-factor-authentication": "key.horizontal",
  "weather-night": "moon.stars.fill",
  "weather-sunny": "sun.max.fill",
  "weather-sunset-down": "sunset.fill",
  "weather-sunset-up": "sunrise.fill",
  "white-balance-sunny": "sun.max.fill",
  widget: "square.grid.2x2.fill",
  widgets: "square.grid.2x2",
  wifi: "wifi",
  "wifi-off": "wifi.slash",
} as const satisfies Record<string, SFSymbol>;

/** Correspondances Ionicons (noms Expo) → SF Symbol. */
export const ION_TO_SF = {
  "add-circle": "plus.circle.fill",
  "alert-circle": "exclamationmark.circle.fill",
  analytics: "chart.bar.fill",
  book: "book.fill",
  "book-outline": "book",
  bulb: "lightbulb.fill",
  calendar: "calendar",
  checkmark: "checkmark",
  "checkmark-circle": "checkmark.circle.fill",
  "chevron-back": "chevron.left",
  "chevron-down": "chevron.down",
  "chevron-forward": "chevron.right",
  close: "xmark",
  "cloud-offline": "icloud.slash",
  "cloud-offline-outline": "icloud.slash",
  "cloud-download-outline": "icloud.and.arrow.down",
  "color-palette-outline": "paintpalette",
  create: "pencil",
  "document-text": "doc.text",
  "eye-outline": "eye",
  "eye-off": "eye.slash",
  flame: "flame.fill",
  gift: "gift.fill",
  heart: "heart.fill",
  "images-outline": "photo.on.rectangle",
  library: "books.vertical",
  "library-outline": "books.vertical",
  "location-outline": "mappin",
  "lock-closed": "lock.fill",
  moon: "moon.fill",
  notifications: "bell",
  refresh: "arrow.clockwise",
  search: "magnifyingglass",
  "settings-outline": "gearshape",
  share: "square.and.arrow.up",
  "share-outline": "square.and.arrow.up",
  "share-social": "square.and.arrow.up.on.square",
  star: "star.fill",
  sync: "arrow.triangle.2.circlepath",
  time: "clock",
  "time-outline": "clock",
  trophy: "trophy.fill",
  "trophy-outline": "trophy",
} as const satisfies Record<string, SFSymbol>;

/** Correspondances Material Icons → SF Symbol. */
export const MI_TO_SF = {
  "chevron-left": "chevron.left",
  "chevron-right": "chevron.right",
} as const satisfies Record<string, SFSymbol>;

function resolveSf(
  map: Record<string, SFSymbol>,
  name: string
): SFSymbol | null {
  const sf = map[name];
  if (!sf || IOS_UNSAFE_SF.has(sf)) {
    return null;
  }
  return sf;
}

/** Retourne null si pas de correspondance ou symbole non sûr → police MaterialCommunityIcons. */
export function mciToSf(name: string): SFSymbol | null {
  return resolveSf(MCI_TO_SF as Record<string, SFSymbol>, name);
}

export function ionToSf(name: string): SFSymbol | null {
  return resolveSf(ION_TO_SF as Record<string, SFSymbol>, name);
}

export function miToSf(name: string): SFSymbol | null {
  return resolveSf(MI_TO_SF as Record<string, SFSymbol>, name);
}
