// abudawoodChapters.js

export const abudawoodChapters = [
  {
    number: 1,
    english: "Purification (Kitab Al-Taharah)",
    arabic: "كتاب الطهارة",
    from: 1,
    to: 390,
  },
  {
    number: 2,
    english: "Prayer (Kitab Al-Salat)",
    arabic: "كتاب الصلاة",
    from: 391,
    to: 1160,
  },
  {
    number: 3,
    english: "The Book Of The Prayer For Rain (Kitab al-Istisqa')",
    arabic: "كتاب الاستسقاء",
    from: 1161,
    to: 1197,
  },
  {
    number: 4,
    english:
      "Prayer (Kitab Al-Salat): Detailed Rules of Law about the Prayer during Journey",
    arabic: "كتاب صلاة السفر",
    from: 1198,
    to: 1249,
  },
  {
    number: 5,
    english: "Prayer (Kitab Al-Salat): Voluntary Prayers",
    arabic: "كتاب التطوع",
    from: 1250,
    to: 1370,
  },
  {
    number: 6,
    english: "Prayer (Kitab Al-Salat): Detailed Injunctions about Ramadan",
    arabic: "كتاب شهر رمضان",
    from: 1371,
    to: 1400,
  },
  {
    number: 7,
    english: "Prayer (Kitab Al-Salat): Prostration while reciting the Qur'an",
    arabic: "كتاب سجود القرآن",
    from: 1401,
    to: 1415,
  },
  {
    number: 8,
    english: "Prayer (Kitab Al-Salat): Detailed Injunctions about Witr",
    arabic: "كتاب الوتر",
    from: 1416,
    to: 1555,
  },
  {
    number: 9,
    english: "Zakat (Kitab Al-Zakat)",
    arabic: "كتاب الزكاة",
    from: 1556,
    to: 1700,
  },
  {
    number: 10,
    english: "The Book of Lost and Found Items",
    arabic: "كتاب اللقطة",
    from: 1701,
    to: 1720,
  },
  {
    number: 11,
    english: "The Rites of Hajj (Kitab Al-Manasik Wa'l-Hajj)",
    arabic: "كتاب المناسك",
    from: 1721,
    to: 2045,
  },
  {
    number: 12,
    english: "Marriage (Kitab Al-Nikah)",
    arabic: "كتاب النكاح",
    from: 2046,
    to: 2174,
  },
  {
    number: 13,
    english: "Divorce (Kitab Al-Talaq)",
    arabic: "كتاب الطلاق",
    from: 2175,
    to: 2312,
  },
  {
    number: 14,
    english: "Fasting (Kitab Al-Siyam)",
    arabic: "كتاب الصوم",
    from: 2313,
    to: 2476,
  },
  {
    number: 15,
    english: "Jihad (Kitab Al-Jihad)",
    arabic: "كتاب الجهاد",
    from: 2477,
    to: 2787,
  },
  {
    number: 16,
    english: "Sacrifice (Kitab Al-Dahaya)",
    arabic: "كتاب الضحايا",
    from: 2788,
    to: 2843,
  },
  {
    number: 17,
    english: "Game (Kitab Al-Said)",
    arabic: "كتاب الصيد",
    from: 2844,
    to: 2861,
  },
  {
    number: 18,
    english: "Wills (Kitab Al-Wasaya)",
    arabic: "كتاب الوصايا",
    from: 2862,
    to: 2884,
  },
  {
    number: 19,
    english: "Shares of Inheritance (Kitab Al-Fara'id)",
    arabic: "كتاب الفرائض",
    from: 2885,
    to: 2927,
  },
  {
    number: 20,
    english:
      "Tribute, Spoils, and Rulership (Kitab Al-Kharaj, Wal-Fai' Wal-Imarah)",
    arabic: "كتاب الخراج والإمارة والفىء",
    from: 2928,
    to: 3088,
  },
  {
    number: 21,
    english: "Funerals (Kitab Al-Jana'iz)",
    arabic: "كتاب الجنائز",
    from: 3089,
    to: 3241,
  },
  {
    number: 22,
    english: "Oaths and Vows (Kitab Al-Aiman Wa Al-Nudhur)",
    arabic: "كتاب الأيمان والنذور",
    from: 3242,
    to: 3325,
  },
  {
    number: 23,
    english: "Commercial Transactions (Kitab Al-Buyu)",
    arabic: "كتاب البيوع",
    from: 3326,
    to: 3415,
  },
  {
    number: 24,
    english: "Wages (Kitab Al-Ijarah)",
    arabic: "كتاب الإجارة",
    from: 3416,
    to: 3570,
  },
  {
    number: 25,
    english: "The Office of the Judge (Kitab Al-Aqdiyah)",
    arabic: "كتاب الأقضية",
    from: 3571,
    to: 3640,
  },
  {
    number: 26,
    english: "Knowledge (Kitab Al-Ilm)",
    arabic: "كتاب العلم",
    from: 3641,
    to: 3668,
  },
  {
    number: 27,
    english: "Drinks (Kitab Al-Ashribah)",
    arabic: "كتاب الأشربة",
    from: 3669,
    to: 3735,
  },
  {
    number: 28,
    english: "Foods (Kitab Al-At'imah)",
    arabic: "كتاب الأطعمة",
    from: 3736,
    to: 3854,
  },
  {
    number: 29,
    english: "Medicine (Kitab Al-Tibb)",
    arabic: "كتاب الطب",
    from: 3855,
    to: 3903,
  },
  {
    number: 30,
    english: "Divination and Omens (Kitab Al-Kahanah Wa Al-Tatayyur)",
    arabic: "كتاب الكهانة و التطير",
    from: 3904,
    to: 3925,
  },
  {
    number: 31,
    english: "The Book of Manumission of Slaves",
    arabic: "كتاب العتق",
    from: 3926,
    to: 3968,
  },
  {
    number: 32,
    english:
      "Dialects and Readings of the Qur'an (Kitab Al-Huruf Wa Al-Qira'at)",
    arabic: "كتاب الحروف والقراءات",
    from: 3969,
    to: 4008,
  },
  {
    number: 33,
    english: "Hot Baths (Kitab Al-Hammam)",
    arabic: "كتاب الحمَّام",
    from: 4009,
    to: 4019,
  },
  {
    number: 34,
    english: "Clothing (Kitab Al-Libas)",
    arabic: "كتاب اللباس",
    from: 4020,
    to: 4158,
  },
  {
    number: 35,
    english: "Combing the Hair (Kitab Al-Tarajjul)",
    arabic: "كتاب الترجل",
    from: 4159,
    to: 4213,
  },
  {
    number: 36,
    english: "Signet-Rings (Kitab Al-Khatam)",
    arabic: "كتاب الخاتم",
    from: 4214,
    to: 4239,
  },
  {
    number: 37,
    english: "Trials and Fierce Battles (Kitab Al-Fitan Wa Al-Malahim)",
    arabic: "كتاب الفتن والملاحم",
    from: 4240,
    to: 4278,
  },
  {
    number: 38,
    english: "The Promised Deliverer (Kitab Al-Mahdi)",
    arabic: "كتاب المهدى",
    from: 4279,
    to: 4290,
  },
  {
    number: 39,
    english: "Battles (Kitab Al-Malahim)",
    arabic: "كتاب الملاحم",
    from: 4291,
    to: 4350,
  },
  {
    number: 40,
    english: "Prescribed Punishments (Kitab Al-Hudud)",
    arabic: "كتاب الحدود",
    from: 4351,
    to: 4493,
  },
  {
    number: 41,
    english: "Types of Blood-Wit (Kitab Al-Diyat)",
    arabic: "كتاب الديات",
    from: 4494,
    to: 4595,
  },
  {
    number: 42,
    english: "Model Behavior of the Prophet (Kitab Al-Sunnah)",
    arabic: "كتاب السنة",
    from: 4596,
    to: 4772,
  },
  {
    number: 43,
    english: "General Behavior (Kitab Al-Adab)",
    arabic: "كتاب الأدب",
    from: 4773,
    to: 5274,
  },
];
