// bukhariChapters.js

export const bukhariChapters = [
  {
    number: 1,
    english: "Revelation",
    arabic: "كتاب بدء الوحى",
    from: 1,
    to: 7,
  },
  {
    number: 2,
    english: "Belief",
    arabic: "كتاب الإيمان",
    from: 8,
    to: 58,
  },
  {
    number: 3,
    english: "Knowledge",
    arabic: "كتاب العلم",
    from: 59,
    to: 134,
  },
  {
    number: 4,
    english: "Ablutions (Wudu')",
    arabic: "كتاب الوضوء",
    from: 135,
    to: 247,
  },
  {
    number: 5,
    english: "Bathing (Ghusl)",
    arabic: "كتاب الغسل",
    from: 248,
    to: 293,
  },
  {
    number: 6,
    english: "Menstrual Periods",
    arabic: "كتاب الحيض",
    from: 294,
    to: 333,
  },
  {
    number: 7,
    english: "Rubbing hands and feet with dust (Tayammum)",
    arabic: "كتاب التيمم",
    from: 334,
    to: 348,
  },
  {
    number: 8,
    english: "Prayers (Salat)",
    arabic: "كتاب الصلاة",
    from: 349,
    to: 520,
  },
  {
    number: 9,
    english: "Times of the Prayers",
    arabic: "كتاب مواقيت الصلاة",
    from: 521,
    to: 602,
  },
  {
    number: 10,
    english: "Call to Prayers (Adhaan)",
    arabic: "كتاب الأذان",
    from: 603,
    to: 875,
  },
  {
    number: 11,
    english: "Friday Prayer",
    arabic: "كتاب الجمعة",
    from: 876,
    to: 941,
  },
  {
    number: 12,
    english: "Fear Prayer",
    arabic: "كتاب صلاة الخوف",
    from: 942,
    to: 947,
  },
  {
    number: 13,
    english: "The Two Festivals (Eids)",
    arabic: "كتاب العيدين",
    from: 948,
    to: 989,
  },
  {
    number: 14,
    english: "Witr Prayer",
    arabic: "كتاب الوتر",
    from: 990,
    to: 1004,
  },
  {
    number: 15,
    english: "Invoking Allah for Rain (Istisqaa)",
    arabic: "كتاب الاستسقاء",
    from: 1005,
    to: 1039,
  },
  {
    number: 16,
    english: "Eclipses",
    arabic: "كتاب الكسوف",
    from: 1040,
    to: 1065,
  },
  {
    number: 17,
    english: "Prostration During Recital of Qur'an",
    arabic: "كتاب سجود القرآن",
    from: 1067,
    to: 1079,
  },
  {
    number: 18,
    english: "Shortening the Prayers (At-Taqseer)",
    arabic: "كتاب التقصير",
    from: 1080,
    to: 1119,
  },
  {
    number: 19,
    english: "Prayer at Night (Tahajjud)",
    arabic: "كتاب التهجد",
    from: 1120,
    to: 1187,
  },
  {
    number: 20,
    english: "Virtues of Prayer at Masjid Makkah and Madinah",
    arabic: "كتاب فضل الصلاة فى مسجد مكة والمدينة",
    from: 1188,
    to: 1197,
  },
  {
    number: 21,
    english: "Actions while Praying",
    arabic: "كتاب العمل فى الصلاة",
    from: 1198,
    to: 1223,
  },
  {
    number: 22,
    english: "Forgetfulness in Prayer",
    arabic: "كتاب السهو",
    from: 1224,
    to: 1236,
  },
  {
    number: 23,
    english: "Funerals (Al-Janaa'iz)",
    arabic: "كتاب الجنائز",
    from: 1237,
    to: 1394,
  },
  {
    number: 24,
    english: "Obligatory Charity Tax (Zakat)",
    arabic: "كتاب الزكاة",
    from: 1395,
    to: 1512,
  },
  {
    number: 25,
    english: "Hajj (Pilgrimage)",
    arabic: "كتاب الحج",
    from: 1513,
    to: 1771,
  },
  {
    number: 26,
    english: "`Umrah (Minor pilgrimage)",
    arabic: "كتاب العمرة",
    from: 1773,
    to: 1805,
  },
  {
    number: 27,
    english: "Pilgrims Prevented from Completing the Pilgrimage",
    arabic: "كتاب المحصر",
    from: 1806,
    to: 1820,
  },
  {
    number: 28,
    english: "Penalty of Hunting while on Pilgrimage",
    arabic: "كتاب جزاء الصيد",
    from: 1821,
    to: 1866,
  },
  {
    number: 29,
    english: "Virtues of Madinah",
    arabic: "كتاب فضائل المدينة",
    from: 1867,
    to: 1890,
  },
  {
    number: 30,
    english: "Fasting",
    arabic: "كتاب الصوم",
    from: 1891,
    to: 2007,
  },
  {
    number: 31,
    english: "Praying at Night in Ramadaan (Taraweeh)",
    arabic: "كتاب صلاة التراويح",
    from: 2008,
    to: 2013,
  },
  {
    number: 32,
    english: "Virtues of the Night of Qadr",
    arabic: "كتاب فضل ليلة القدر",
    from: 2014,
    to: 2024,
  },
  {
    number: 33,
    english: "Retiring to a Mosque for Remembrance of Allah (I'tikaf)",
    arabic: "كتاب الاعتكاف",
    from: 2025,
    to: 2046,
  },
  {
    number: 34,
    english: "Sales and Trade",
    arabic: "كتاب البيوع",
    from: 2047,
    to: 2238,
  },
  {
    number: 35,
    english:
      "Sales in which a Price is paid for Goods to be Delivered Later (As-Salam)",
    arabic: "كتاب السلم",
    from: 2239,
    to: 2256,
  },
  {
    number: 36,
    english: "Shuf'a",
    arabic: "كتاب الشفعة",
    from: 2257,
    to: 2259,
  },
  {
    number: 37,
    english: "Hiring",
    arabic: "كتاب الإجارة",
    from: 2260,
    to: 2285,
  },
  {
    number: 38,
    english: "Transferance of a Debt from One Person to Another (Al-Hawaala)",
    arabic: "كتاب الحوالات",
    from: 2287,
    to: 2289,
  },
  {
    number: 39,
    english: "Kafalah",
    arabic: "كتاب الكفالة",
    from: 2290,
    to: 2298,
  },
  {
    number: 40,
    english: "Representation, Authorization, Business by Proxy",
    arabic: "كتاب الوكالة",
    from: 2299,
    to: 2319,
  },
  {
    number: 41,
    english: "Agriculture",
    arabic: "كتاب المزارعة",
    from: 2320,
    to: 2350,
  },
  {
    number: 42,
    english: "Distribution of Water",
    arabic: "كتاب المساقاة",
    from: 2351,
    to: 2383,
  },
  {
    number: 43,
    english: "Loans, Payment of Loans, Freezing of Property, Bankruptcy",
    arabic: "كتاب فى الاستقراض",
    from: 2385,
    to: 2409,
  },
  {
    number: 44,
    english: "Khusoomaat",
    arabic: "كتاب الخصومات",
    from: 2410,
    to: 2425,
  },
  {
    number: 45,
    english: "Lost Things Picked up by Someone (Luqatah)",
    arabic: "كتاب فى اللقطة",
    from: 2426,
    to: 2439,
  },
  {
    number: 46,
    english: "Oppressions",
    arabic: "كتاب المظالم",
    from: 2440,
    to: 2482,
  },
  {
    number: 47,
    english: "Partnership",
    arabic: "كتاب الشركة",
    from: 2483,
    to: 2507,
  },
  {
    number: 48,
    english: "Mortgaging",
    arabic: "كتاب الرهن",
    from: 2508,
    to: 2515,
  },
  {
    number: 49,
    english: "Manumission of Slaves",
    arabic: "كتاب العتق",
    from: 2517,
    to: 2559,
  },
  {
    number: 50,
    english: "Makaatib",
    arabic: "كتاب المكاتب",
    from: 2560,
    to: 2565,
  },
  {
    number: 51,
    english: "Gifts",
    arabic: "كتاب الهبة وفضلها والتحريض عليها",
    from: 2566,
    to: 2636,
  },
  {
    number: 52,
    english: "Witnesses",
    arabic: "كتاب الشهادات",
    from: 2637,
    to: 2689,
  },
  {
    number: 53,
    english: "Peacemaking",
    arabic: "كتاب الصلح",
    from: 2690,
    to: 2710,
  },
  {
    number: 54,
    english: "Conditions",
    arabic: "كتاب الشروط",
    from: 2711,
    to: 2737,
  },
  {
    number: 55,
    english: "Wills and Testaments (Wasaayaa)",
    arabic: "كتاب الوصايا",
    from: 2738,
    to: 2781,
  },
  {
    number: 56,
    english: "Fighting for the Cause of Allah (Jihaad)",
    arabic: "كتاب الجهاد والسير",
    from: 2782,
    to: 3090,
  },
  {
    number: 57,
    english: "One-fifth of Booty to the Cause of Allah (Khumus)",
    arabic: "كتاب فرض الخمس",
    from: 3091,
    to: 3155,
  },
  {
    number: 58,
    english: "Jizyah and Mawaada'ah",
    arabic: "كتاب الجزية والموادعة",
    from: 3156,
    to: 3189,
  },
  {
    number: 59,
    english: "Beginning of Creation",
    arabic: "كتاب بدء الخلق",
    from: 3190,
    to: 3325,
  },
  {
    number: 60,
    english: "Prophets",
    arabic: "كتاب أحاديث الأنبياء",
    from: 3326,
    to: 3488,
  },
  {
    number: 61,
    english: "Virtues and Merits of the Prophet (pbuh) and his Companions",
    arabic: "كتاب المناقب",
    from: 3489,
    to: 3648,
  },
  {
    number: 62,
    english: "Companions of the Prophet",
    arabic: "كتاب فضائل أصحاب النبى صلى الله عليه وسلم",
    from: 3649,
    to: 3775,
  },
  {
    number: 63,
    english: "Merits of the Helpers in Madinah (Ansaar)",
    arabic: "كتاب مناقب الأنصار",
    from: 3776,
    to: 3948,
  },
  {
    number: 64,
    english: "Military Expeditions led by the Prophet (pbuh) (Al-Maghaazi)",
    arabic: "كتاب المغازى",
    from: 3949,
    to: 4473,
  },
  {
    number: 65,
    english:
      "Prophetic Commentary on the Qur'an (Tafseer of the Prophet (pbuh))",
    arabic: "كتاب التفسير",
    from: 4474,
    to: 4977,
  },
  {
    number: 66,
    english: "Virtues of the Qur'an",
    arabic: "كتاب فضائل القرآن",
    from: 4978,
    to: 5062,
  },
  {
    number: 67,
    english: "Wedlock, Marriage (Nikaah)",
    arabic: "كتاب النكاح",
    from: 5063,
    to: 5250,
  },
  {
    number: 68,
    english: "Divorce",
    arabic: "كتاب الطلاق",
    from: 5251,
    to: 5350,
  },
  {
    number: 69,
    english: "Supporting the Family",
    arabic: "كتاب النفقات",
    from: 5351,
    to: 5372,
  },
  {
    number: 70,
    english: "Food, Meals",
    arabic: "كتاب الأطعمة",
    from: 5373,
    to: 5466,
  },
  {
    number: 71,
    english: "Sacrifice on Occasion of Birth (`Aqiqa)",
    arabic: "كتاب العقيقة",
    from: 5467,
    to: 5474,
  },
  {
    number: 72,
    english: "Hunting, Slaughtering",
    arabic: "كتاب الذبائح والصيد",
    from: 5475,
    to: 5544,
  },
  {
    number: 73,
    english: "Al-Adha Festival Sacrifice (Adaahi)",
    arabic: "كتاب الأضاحي",
    from: 5545,
    to: 5574,
  },
  {
    number: 74,
    english: "Drinks",
    arabic: "كتاب الأشربة",
    from: 5575,
    to: 5639,
  },
  {
    number: 75,
    english: "Patients",
    arabic: "كتاب المرضى",
    from: 5640,
    to: 5677,
  },
  {
    number: 76,
    english: "Medicine",
    arabic: "كتاب الطب",
    from: 5678,
    to: 5782,
  },
  {
    number: 77,
    english: "Dress",
    arabic: "كتاب اللباس",
    from: 5783,
    to: 5969,
  },
  {
    number: 78,
    english: "Good Manners and Form (Al-Adab)",
    arabic: "كتاب الأدب",
    from: 5970,
    to: 6226,
  },
  {
    number: 79,
    english: "Asking Permission",
    arabic: "كتاب الاستئذان",
    from: 6227,
    to: 6303,
  },
  {
    number: 80,
    english: "Invocations",
    arabic: "كتاب الدعوات",
    from: 6304,
    to: 6411,
  },
  {
    number: 81,
    english: "To make the Heart Tender (Ar-Riqaq)",
    arabic: "كتاب الرقاق",
    from: 6412,
    to: 6593,
  },
  {
    number: 82,
    english: "Divine Will (Al-Qadar)",
    arabic: "كتاب القدر",
    from: 6594,
    to: 6620,
  },
  {
    number: 83,
    english: "Oaths and Vows",
    arabic: "كتاب الأيمان والنذور",
    from: 6621,
    to: 6707,
  },
  {
    number: 84,
    english: "Expiation for Unfulfilled Oaths",
    arabic: "كتاب كفارات الأيمان",
    from: 6708,
    to: 6722,
  },
  {
    number: 85,
    english: "Laws of Inheritance (Al-Faraa'id)",
    arabic: "كتاب الفرائض",
    from: 6723,
    to: 6771,
  },
  {
    number: 86,
    english: "Limits and Punishments set by Allah (Hudood)",
    arabic: "كتاب الحدود",
    from: 6772,
    to: 6859,
  },
  {
    number: 87,
    english: "Blood Money (Ad-Diyat)",
    arabic: "كتاب الديات",
    from: 6861,
    to: 6917,
  },
  {
    number: 88,
    english: "Apostates",
    arabic: "كتاب استتابة المرتدين والمعاندين وقتالهم",
    from: 6918,
    to: 6939,
  },
  {
    number: 89,
    english: "(Statements made under) Coercion",
    arabic: "كتاب الإكراه",
    from: 6940,
    to: 6952,
  },
  {
    number: 90,
    english: "Tricks",
    arabic: "كتاب الحيل",
    from: 6953,
    to: 6981,
  },
  {
    number: 91,
    english: "Interpretation of Dreams",
    arabic: "كتاب التعبير",
    from: 6982,
    to: 7047,
  },
  {
    number: 92,
    english: "Afflictions and the End of the World",
    arabic: "كتاب الفتن",
    from: 7048,
    to: 7136,
  },
  {
    number: 93,
    english: "Judgments (Ahkaam)",
    arabic: "كتاب الأحكام",
    from: 7137,
    to: 7225,
  },
  {
    number: 94,
    english: "Wishes",
    arabic: "كتاب التمنى",
    from: 7226,
    to: 7245,
  },
  {
    number: 95,
    english: "Accepting Information Given by a Truthful Person",
    arabic: "كتاب أخبار الآحاد",
    from: 7246,
    to: 7267,
  },
  {
    number: 96,
    english: "Holding Fast to the Qur'an and Sunnah",
    arabic: "كتاب الاعتصام بالكتاب والسنة",
    from: 7268,
    to: 7370,
  },
  {
    number: 97,
    english: "Oneness, Uniqueness of Allah (Tawheed)",
    arabic: "كتاب التوحيد",
    from: 7371,
    to: 7563,
  },
];
