// ibnMajahChapters.js

export const ibnmajahChapters = [
  {
    number: 0,
    english: "The Book of the Sunnah",
    arabic: "كتاب المقدمة",
    from: 1,
    to: 266,
  },
  {
    number: 1,
    english: "The Book of Purification and its Sunnah",
    arabic: "كتاب الطهارة وسننها",
    from: 267,
    to: 666,
  },
  {
    number: 2,
    english: "The Book of the Prayer",
    arabic: "كتاب الصلاة",
    from: 667,
    to: 705,
  },
  {
    number: 3,
    english: "The Book of the Adhan and the Sunnah Regarding It",
    arabic: "كتاب الأذان والسنة فيها",
    from: 706,
    to: 734,
  },
  {
    number: 4,
    english: "The Book On The Mosques And The Congregations",
    arabic: "كتاب المساجد والجماعات",
    from: 735,
    to: 802,
  },
  {
    number: 5,
    english: "Establishing the Prayer and the Sunnah Regarding Them",
    arabic: "كتاب إقامة الصلاة والسنة فيها",
    from: 803,
    to: 1432,
  },
  {
    number: 6,
    english: "Chapters Regarding Funerals",
    arabic: "كتاب الجنائز",
    from: 1433,
    to: 1637,
  },
  {
    number: 7,
    english: "Fasting",
    arabic: "كتاب الصيام",
    from: 1638,
    to: 1782,
  },
  {
    number: 8,
    english: "The Chapters Regarding Zakat",
    arabic: "كتاب الزكاة",
    from: 1783,
    to: 1844,
  },
  {
    number: 9,
    english: "The Chapters on Marriage",
    arabic: "كتاب النكاح",
    from: 1845,
    to: 2015,
  },
  {
    number: 10,
    english: "The Chapters on Divorce",
    arabic: "كتاب الطلاق",
    from: 2016,
    to: 2477,
  },
  {
    number: 11,
    english: "The Chapters on Expiation",
    arabic: "كتاب الكفارات",
    from: 2090,
    to: 2136,
  },
  {
    number: 12,
    english: "The Chapters on Business Transactions",
    arabic: "كتاب التجارات",
    from: 2137,
    to: 2307,
  },
  {
    number: 13,
    english: "The Chapters on Rulings",
    arabic: "كتاب الأحكام",
    from: 2308,
    to: 2374,
  },
  {
    number: 14,
    english: "The Chapters on Gifts",
    arabic: "كتاب الهبات",
    from: 2375,
    to: 2389,
  },
  {
    number: 15,
    english: "The Chapters on Charity",
    arabic: "كتاب الصدقات",
    from: 2390,
    to: 2528,
  },
  {
    number: 16,
    english: "The Chapters on Pawning",
    arabic: "كتاب الرهون",
    from: 2436,
    to: 2491,
  },
  {
    number: 17,
    english: "The Chapters on Pre-emption",
    arabic: "كتاب الشفعة",
    from: 2492,
    to: 2501,
  },
  {
    number: 18,
    english: "The Chapters on Lost Property",
    arabic: "كتاب اللقطة",
    from: 2502,
    to: 2511,
  },
  {
    number: 19,
    english: "The Chapters on Manumission (of Slaves)",
    arabic: "كتاب العتق",
    from: 2512,
    to: 2532,
  },
  {
    number: 20,
    english: "The Chapters on Legal Punishments",
    arabic: "كتاب الحدود",
    from: 2533,
    to: 2614,
  },
  {
    number: 21,
    english: "The Chapters on Blood Money",
    arabic: "كتاب الديات",
    from: 2615,
    to: 2694,
  },
  {
    number: 22,
    english: "The Chapters on Wills",
    arabic: "كتاب الوصايا",
    from: 2695,
    to: 2718,
  },
  {
    number: 23,
    english: "Chapters on Shares of Inheritance",
    arabic: "كتاب الفرائض",
    from: 2719,
    to: 2752,
  },
  {
    number: 24,
    english: "The Chapters on Jihad",
    arabic: "كتاب الجهاد",
    from: 2753,
    to: 2881,
  },
  {
    number: 25,
    english: "Chapters on Hajj Rituals",
    arabic: "كتاب المناسك",
    from: 2882,
    to: 3119,
  },
  {
    number: 26,
    english: "Chapters on Sacrifices",
    arabic: "كتاب الأضاحي",
    from: 3120,
    to: 3161,
  },
  {
    number: 27,
    english: "Chapters on Slaughtering",
    arabic: "كتاب الذبائح",
    from: 3162,
    to: 3199,
  },
  {
    number: 28,
    english: "Chapters on Hunting",
    arabic: "كتاب الصيد",
    from: 3200,
    to: 3250,
  },
  {
    number: 29,
    english: "Chapters on Food",
    arabic: "كتاب الأطعمة",
    from: 3251,
    to: 3370,
  },
  {
    number: 30,
    english: "Chapters on Drinks",
    arabic: "كتاب الأشربة",
    from: 3371,
    to: 3435,
  },
  {
    number: 31,
    english: "Chapters on Medicine",
    arabic: "كتاب الطب",
    from: 3436,
    to: 3549,
  },
  {
    number: 32,
    english: "Chapters on Dress",
    arabic: "كتاب اللباس",
    from: 3550,
    to: 3656,
  },
  {
    number: 33,
    english: "Etiquette",
    arabic: "كتاب الأدب",
    from: 3657,
    to: 3826,
  },
  {
    number: 34,
    english: "Supplication",
    arabic: "كتاب الدعاء",
    from: 3827,
    to: 3892,
  },
  {
    number: 35,
    english: "Interpretation of Dreams",
    arabic: "كتاب تعبير الرؤيا",
    from: 3893,
    to: 3926,
  },
  {
    number: 36,
    english: "Tribulations",
    arabic: "كتاب الفتن",
    from: 3927,
    to: 4099,
  },
  {
    number: 37,
    english: "Zuhd",
    arabic: "كتاب الزهد",
    from: 4100,
    to: 4341,
  },
];
