// mishkatChapters.js

export const mishkatChapters = [
  {
    number: 0,
    english: "Author's Introduction",
    arabic: "مقدمة المؤلف",
    from: 1,
    to: 1,
  },
  {
    number: 1,
    english: "Faith",
    arabic: "كتاب الإيمان",
    from: 2,
    to: 197,
  },
  {
    number: 2,
    english: "Knowledge",
    arabic: "كتاب العلم",
    from: 198,
    to: 280,
  },
  {
    number: 3,
    english: "Purification",
    arabic: "كتاب الطهارة",
    from: 281,
    to: 562,
  },
  {
    number: 4,
    english: "Prayer",
    arabic: "كتاب الصلاة",
    from: 564,
    to: 1522,
  },
  {
    number: 5,
    english: "Funerals",
    arabic: "كتاب الجنائز",
    from: 1523,
    to: 1771,
  },
  {
    number: 6,
    english: "Zakat",
    arabic: "كتاب الزكاة",
    from: 1772,
    to: 1955,
  },
  {
    number: 7,
    english: "Fasting",
    arabic: "كتاب الصوم",
    from: 1956,
    to: 2108,
  },
  {
    number: 8,
    english: "The Excellent Qualities of the Qur'an",
    arabic: "كتاب فضائل القرآن",
    from: 2109,
    to: 2222,
  },
  {
    number: 9,
    english: "Supplications",
    arabic: "كتاب الدعوات",
    from: 2223,
    to: 2504,
  },
  {
    number: 10,
    english: "The Rites of Pilgrimage",
    arabic: "كتاب المناسك",
    from: 2505,
    to: 2758,
  },
  {
    number: 11,
    english: "Business Transactions",
    arabic: "كتاب البيوع",
    from: 2759,
    to: 3040,
  },
  {
    number: 12,
    english: "Inheritance and Wills",
    arabic: "كتاب الفرائض والوصايا",
    from: 3041,
    to: 3078,
  },
  {
    number: 13,
    english: "Marriage",
    arabic: "كتاب النكاح",
    from: 3080,
    to: 3381,
  },
  {
    number: 14,
    english: "Emancipation",
    arabic: "كتاب العتق",
    from: 3382,
    to: 3405,
  },
  {
    number: 15,
    english: "Oaths and Vows",
    arabic: "كتاب الإيمان والنذور",
    from: 3406,
    to: 3445,
  },
  {
    number: 16,
    english: "Retaliation",
    arabic: "كتاب القصاص",
    from: 3446,
    to: 3554,
  },
  {
    number: 17,
    english: "Prescribed Punishments",
    arabic: "كتاب الحدود",
    from: 3555,
    to: 3660,
  },
  {
    number: 18,
    english: "The Offices of Commander and Qadi",
    arabic: "كتاب الإمارة والقضاء",
    from: 3661,
    to: 3786,
  },
  {
    number: 19,
    english: "Jihad",
    arabic: "كتاب الجهاد",
    from: 3787,
    to: 4063,
  },
  {
    number: 20,
    english: "Game and Animals Which May Be Slaughtered",
    arabic: "كتاب الصيد والذبائح",
    from: 4064,
    to: 4158,
  },
  {
    number: 21,
    english: "Foods",
    arabic: "كتاب الأطعمة",
    from: 4159,
    to: 4303,
  },
  {
    number: 22,
    english: "Clothing",
    arabic: "كتاب اللباس",
    from: 4304,
    to: 4513,
  },
  {
    number: 23,
    english: "Medicine and Spells",
    arabic: "كتاب الطب والرقى",
    from: 4514,
    to: 4605,
  },
  {
    number: 24,
    english: "Visions",
    arabic: "كتاب الرؤيا",
    from: 4606,
    to: 4627,
  },
  {
    number: 27,
    english: "Fitan",
    arabic: "كتاب الفتن",
    from: 5379,
    to: 5520,
  },
  {
    number: 28,
    english: "Events of the Day of Resurrection and the Beginning of Creation",
    arabic: "كتاب أحوال القيامة وبدء الخلق",
    from: 5521,
    to: 5738,
  },
  {
    number: 29,
    english: "Excellent Qualities and Description of the Prophet",
    arabic: "كتاب الفضائل والشمائل",
    from: 5739,
    to: 5978,
  },
];
