// muslimChapters.js

export const muslimChapters = [
  {
    number: 0,
    english: "Introduction",
    arabic: "المقدمة",
    from: 1,
    to: 7,
  },
  {
    number: 1,
    english: "The Book of Faith",
    arabic: "كتاب الإيمان",
    from: 8,
    to: 222,
  },
  {
    number: 2,
    english: "The Book of Purification",
    arabic: "كتاب الطهارة",
    from: 223,
    to: 292,
  },
  {
    number: 3,
    english: "The Book of Menstruation",
    arabic: "كتاب الحيض",
    from: 293,
    to: 376,
  },
  {
    number: 4,
    english: "The Book of Prayers",
    arabic: "كتاب الصلاة",
    from: 377,
    to: 519,
  },
  {
    number: 5,
    english: "The Book of Mosques and Places of Prayer",
    arabic: "كتاب الْمَسَاجِدِ وَمَوَاضِعِ الصَّلاَةِ",
    from: 520,
    to: 684,
  },
  {
    number: 6,
    english: "The Book of Prayer - Travellers",
    arabic: "كتاب صلاة المسافرين وقصرها",
    from: 685,
    to: 843,
  },
  {
    number: 7,
    english: "The Book of Prayer - Friday",
    arabic: "كتاب الجمعة",
    from: 844,
    to: 883,
  },
  {
    number: 8,
    english: "The Book of Prayer - Two Eids",
    arabic: "كتاب صلاة العيدين",
    from: 884,
    to: 893,
  },
  {
    number: 9,
    english: "The Book of Prayer - Rain",
    arabic: "كتاب صلاة الاستسقاء‏",
    from: 894,
    to: 900,
  },
  {
    number: 10,
    english: "The Book of Prayer - Eclipses",
    arabic: "كتاب الكسوف",
    from: 901,
    to: 915,
  },
  {
    number: 11,
    english: "The Book of Prayer - Funerals",
    arabic: "كتاب الجنائز",
    from: 916,
    to: 978,
  },
  {
    number: 12,
    english: "The Book of Zakat",
    arabic: "كتاب الزكاة",
    from: 979,
    to: 1078,
  },
  {
    number: 13,
    english: "The Book of Fasting",
    arabic: "كتاب الصيام",
    from: 1079,
    to: 1170,
  },
  {
    number: 14,
    english: "The Book of I'tikaf",
    arabic: "كتاب الاعتكاف",
    from: 1171,
    to: 1176,
  },
  {
    number: 15,
    english: "The Book of Pilgrimage",
    arabic: "كتاب الحج",
    from: 1177,
    to: 1399,
  },
  {
    number: 16,
    english: "The Book of Marriage",
    arabic: "كتاب النكاح",
    from: 1400,
    to: 1443,
  },
  {
    number: 17,
    english: "The Book of Suckling",
    arabic: "كتاب الرضاع",
    from: 1444,
    to: 1470,
  },
  {
    number: 18,
    english: "The Book of Divorce",
    arabic: "كتاب الطلاق",
    from: 1471,
    to: 1491,
  },
  {
    number: 19,
    english: "The Book of Invoking Curses",
    arabic: "كتاب اللعان",
    from: 1492,
    to: 1500,
  },
  {
    number: 20,
    english: "The Book of Emancipating Slaves",
    arabic: "كتاب العتق",
    from: 1501,
    to: 1510,
  },
  {
    number: 21,
    english: "The Book of Transactions",
    arabic: "كتاب البيوع",
    from: 1511,
    to: 1550,
  },
  {
    number: 22,
    english: "The Book of Musaqah",
    arabic: "كتاب المساقاة",
    from: 1551,
    to: 1613,
  },
  {
    number: 23,
    english: "The Book of the Rules of Inheritance",
    arabic: "كتاب الفرائض",
    from: 1614,
    to: 1619,
  },
  {
    number: 24,
    english: "The Book of Gifts",
    arabic: "كتاب الهبات",
    from: 1620,
    to: 1626,
  },
  {
    number: 25,
    english: "The Book of Wills",
    arabic: "كتاب الوصية",
    from: 1627,
    to: 1637,
  },
  {
    number: 26,
    english: "The Book of Vows",
    arabic: "كتاب النذر",
    from: 1638,
    to: 1645,
  },
  {
    number: 27,
    english: "The Book of Oaths",
    arabic: "كتاب الأيمان",
    from: 1646,
    to: 1668,
  },
  {
    number: 28,
    english:
      "The Book of Oaths, Muharibin, Qasas (Retaliation), and Diyat (Blood Money)",
    arabic: "كتاب القسامة والمحاربين والقصاص والديات",
    from: 1669,
    to: 1683,
  },
  {
    number: 29,
    english: "The Book of Legal Punishments",
    arabic: "كتاب الحدود",
    from: 1684,
    to: 1710,
  },
  {
    number: 30,
    english: "The Book of Judicial Decisions",
    arabic: "كتاب الأقضية",
    from: 1711,
    to: 1721,
  },
  {
    number: 31,
    english: "The Book of Lost Property",
    arabic: "كتاب اللقطة",
    from: 1722,
    to: 1729,
  },
  {
    number: 32,
    english: "The Book of Jihad and Expeditions",
    arabic: "كتاب الجهاد والسير",
    from: 1730,
    to: 1817,
  },
  {
    number: 33,
    english: "The Book on Government",
    arabic: "كتاب الإمارة",
    from: 1818,
    to: 1928,
  },
  {
    number: 34,
    english: "The Book of Hunting, Slaughter, and what may be Eaten",
    arabic: "كتاب الصيد والذبائح وما يؤكل من الحيوان",
    from: 1929,
    to: 1959,
  },
  {
    number: 35,
    english: "The Book of Sacrifices",
    arabic: "كتاب الأضاحى",
    from: 1960,
    to: 1978,
  },
  {
    number: 36,
    english: "The Book of Drinks",
    arabic: "كتاب الأشربة",
    from: 1979,
    to: 2064,
  },
  {
    number: 37,
    english: "The Book of Clothes and Adornment",
    arabic: "كتاب اللباس والزينة",
    from: 2065,
    to: 2130,
  },
  {
    number: 38,
    english: "The Book of Manners and Etiquette",
    arabic: "كتاب الآداب",
    from: 2131,
    to: 2159,
  },
  {
    number: 39,
    english: "The Book of Greetings",
    arabic: "كتاب السلام",
    from: 2160,
    to: 2245,
  },
  {
    number: 40,
    english: "The Book Concerning the Use of Correct Words",
    arabic: "كتاب الألفاظ من الأدب وغيرها",
    from: 2246,
    to: 2254,
  },
  {
    number: 41,
    english: "The Book of Poetry",
    arabic: "كتاب الشعر",
    from: 2255,
    to: 2260,
  },
  {
    number: 42,
    english: "The Book of Dreams",
    arabic: "كتاب الرؤيا",
    from: 2261,
    to: 2275,
  },
  {
    number: 43,
    english: "The Book of Virtues",
    arabic: "كتاب الفضائل",
    from: 2276,
    to: 2380,
  },
  {
    number: 44,
    english: "The Book of the Merits of the Companions",
    arabic: "كتاب فضائل الصحابة رضى الله تعالى عنهم",
    from: 2381,
    to: 2547,
  },
  {
    number: 45,
    english:
      "The Book of Virtue, Enjoining Good Manners, and Joining of the Ties of Kinship",
    arabic: "كتاب البر والصلة والآداب",
    from: 2548,
    to: 2642,
  },
  {
    number: 46,
    english: "The Book of Destiny",
    arabic: "كتاب القدر",
    from: 2643,
    to: 2664,
  },
  {
    number: 47,
    english: "The Book of Knowledge",
    arabic: "كتاب العلم",
    from: 2665,
    to: 2674,
  },
  {
    number: 48,
    english:
      "The Book Pertaining to the Remembrance of Allah, Supplication, Repentance and Seeking Forgiveness",
    arabic: "كتاب الذكر والدعاء والتوبة والاستغفار",
    from: 2675,
    to: 2735,
  },
  {
    number: 49,
    english: "The Book of Heart-Melting Traditions",
    arabic: "كتاب الرقاق",
    from: 2736,
    to: 2743,
  },
  {
    number: 50,
    english: "The Book of Repentance",
    arabic: "كتاب التوبة",
    from: 2744,
    to: 2771,
  },
  {
    number: 51,
    english: "Characteristics of The Hypocrites And Rulings Concerning Them",
    arabic: "كتاب صفات المنافقين وأحكامهم",
    from: 2772,
    to: 2784,
  },
  {
    number: 52,
    english: "Characteristics of the Day of Judgment, Paradise, and Hell",
    arabic: "كتاب صفة القيامة والجنة والنار",
    from: 2785,
    to: 2821,
  },
  {
    number: 53,
    english:
      "The Book of Paradise, its Description, its Bounties and its Inhabitants",
    arabic: "كتاب الجنة وصفة نعيمها وأهلها",
    from: 2822,
    to: 2879,
  },
  {
    number: 54,
    english: "The Book of Tribulations and Portents of the Last Hour",
    arabic: "كتاب الفتن وأشراط الساعة",
    from: 2880,
    to: 2955,
  },
  {
    number: 55,
    english: "The Book of Zuhd and Softening of Hearts",
    arabic: "كتاب الزهد والرقائق",
    from: 2956,
    to: 3014,
  },
  {
    number: 56,
    english: "The Book of Commentary on the Qur'an",
    arabic: "كتاب التفسير",
    from: 3015,
    to: 3033,
  },
];
