// nasaichapters.js

export const nasaiChapters = [
  {
    number: 1,
    english: "The Book of Purification",
    arabic: "كتاب الطهارة",
    from: 1,
    to: 324,
  },
  {
    number: 2,
    english: "The Book of Water",
    arabic: "كتاب المياه",
    from: 325,
    to: 347,
  },
  {
    number: 3,
    english: "The Book of Menstruation and Istihadah",
    arabic: "كتاب الحيض والاستحاضة",
    from: 348,
    to: 395,
  },
  {
    number: 4,
    english: "The Book of Ghusl and Tayammum",
    arabic: "كتاب الغسل والتيمم",
    from: 396,
    to: 447,
  },
  {
    number: 5,
    english: "The Book of Salah",
    arabic: "كتاب الصلاة",
    from: 448,
    to: 493,
  },
  {
    number: 6,
    english: "The Book of the Times (of Prayer)",
    arabic: "كتاب المواقيت",
    from: 494,
    to: 625,
  },
  {
    number: 7,
    english: "The Book of the Adhan (The Call to Prayer)",
    arabic: "كتاب الأذان",
    from: 626,
    to: 687,
  },
  {
    number: 8,
    english: "The Book of the Masjids",
    arabic: "كتاب المساجد",
    from: 688,
    to: 741,
  },
  {
    number: 9,
    english: "The Book of the Qiblah",
    arabic: "كتاب القبلة",
    from: 742,
    to: 776,
  },
  {
    number: 10,
    english: "The Book of Leading the Prayer (Al-Imamah)",
    arabic: "كتاب الإمامة",
    from: 777,
    to: 875,
  },
  {
    number: 11,
    english: "The Book of the Commencement of the Prayer",
    arabic: "كتاب الافتتاح",
    from: 876,
    to: 1028,
  },
  {
    number: 12,
    english: "The Book of The At-Tatbiq (Clasping One's Hands Together)",
    arabic: "كتاب التطبيق",
    from: 1029,
    to: 1178,
  },
  {
    number: 13,
    english: "The Book of Forgetfulness (In Prayer)",
    arabic: "كتاب السهو",
    from: 1179,
    to: 1366,
  },
  {
    number: 14,
    english: "The Book of Jumu'ah (Friday Prayer)",
    arabic: "كتاب الجمعة",
    from: 1367,
    to: 1432,
  },
  {
    number: 15,
    english: "The Book of Shortening the Prayer When Traveling",
    arabic: "كتاب تقصير الصلاة فى السفر",
    from: 1433,
    to: 1458,
  },
  {
    number: 16,
    english: "The Book of Eclipses",
    arabic: "كتاب الكسوف",
    from: 1459,
    to: 1503,
  },
  {
    number: 17,
    english: "The Book of Praying for Rain (Al-Istisqa')",
    arabic: "كتاب الاستسقاء",
    from: 1504,
    to: 1528,
  },
  {
    number: 18,
    english: "The Book of the Fear Prayer",
    arabic: "كتاب صلاة الخوف",
    from: 1529,
    to: 1555,
  },
  {
    number: 19,
    english: "The Book of the Prayer for the Two 'Eids",
    arabic: "كتاب صلاة العيدين",
    from: 1556,
    to: 1597,
  },
  {
    number: 20,
    english:
      "The Book of Qiyam Al-Lail (The Night Prayer) and Voluntary Prayers During the Day",
    arabic: "كتاب قيام الليل وتطوع النهار",
    from: 1598,
    to: 1817,
  },
  {
    number: 21,
    english: "The Book of Funerals",
    arabic: "كتاب الجنائز",
    from: 1818,
    to: 2089,
  },
  {
    number: 22,
    english: "The Book of Fasting",
    arabic: "كتاب الصيام",
    from: 2090,
    to: 2434,
  },
  {
    number: 23,
    english: "The Book of Zakah",
    arabic: "كتاب الزكاة",
    from: 2435,
    to: 2618,
  },
  {
    number: 24,
    english: "The Book of Hajj",
    arabic: "كتاب مناسك الحج",
    from: 2619,
    to: 3084,
  },
  {
    number: 25,
    english: "The Book of Jihad",
    arabic: "كتاب الجهاد",
    from: 3085,
    to: 3195,
  },
  {
    number: 26,
    english: "The Book of Marriage",
    arabic: "كتاب النكاح",
    from: 3196,
    to: 3388,
  },
  {
    number: 27,
    english: "The Book of Divorce",
    arabic: "كتاب الطلاق",
    from: 3389,
    to: 3560,
  },
  {
    number: 28,
    english: "The Book of Horses, Races and Shooting",
    arabic: "كتاب الخيل",
    from: 3561,
    to: 3593,
  },
  {
    number: 29,
    english: "The Book of Endowments",
    arabic: "كتاب الإحباس",
    from: 3594,
    to: 3610,
  },
  {
    number: 30,
    english: "The Book of Wills",
    arabic: "كتاب الوصايا",
    from: 3611,
    to: 3671,
  },
  {
    number: 31,
    english: "The Book of Presents",
    arabic: "كتاب النحل",
    from: 3672,
    to: 3687,
  },
  {
    number: 32,
    english: "The Book of Gifts",
    arabic: "كتاب الهبة",
    from: 3688,
    to: 3705,
  },
  {
    number: 33,
    english: "The Book of ar-Ruqba",
    arabic: "كتاب الرقبى",
    from: 3706,
    to: 3719,
  },
  {
    number: 34,
    english: "The Book of 'Umra",
    arabic: "كتاب العمرى",
    from: 3720,
    to: 3760,
  },
  {
    number: 35,
    english: "The Book of Oaths and Vows",
    arabic: "كتاب الأيمان والنذور",
    from: 3761,
    to: 3856,
  },
  {
    number: 36,
    english: "The Book of Agriculture",
    arabic: "كتاب المزارعة",
    from: 3857,
    to: 3938,
  },
  {
    number: 37,
    english: "The Book of the Kind Treatment of Women",
    arabic: "كتاب عشرة النساء",
    from: 3939,
    to: 3965,
  },
  {
    number: 38,
    english: "The Book of Fighting [The Prohibition of Bloodshed]",
    arabic: "كتاب تحريم الدم",
    from: 3966,
    to: 4132,
  },
  {
    number: 39,
    english: "The Book of Distribution of Al-Fay'",
    arabic: "كتاب قسم الفىء",
    from: 4133,
    to: 4148,
  },
  {
    number: 40,
    english: "The Book of al-Bay'ah",
    arabic: "كتاب البيعة",
    from: 4149,
    to: 4211,
  },
  {
    number: 41,
    english: "The Book of al-'Aqiqah",
    arabic: "كتاب العقيقة",
    from: 4212,
    to: 4221,
  },
  {
    number: 42,
    english: "The Book of al-Fara' and al-'Atirah",
    arabic: "كتاب الفرع والعتيرة",
    from: 4222,
    to: 4262,
  },
  {
    number: 43,
    english: "The Book of Hunting and Slaughtering",
    arabic: "كتاب الصيد والذبائح",
    from: 4263,
    to: 4360,
  },
  {
    number: 44,
    english: "The Book of ad-Dahaya (Sacrifices)",
    arabic: "كتاب الضحايا",
    from: 4361,
    to: 4448,
  },
  {
    number: 45,
    english: "The Book of Financial Transactions",
    arabic: "كتاب البيوع",
    from: 4449,
    to: 4705,
  },
  {
    number: 46,
    english: "The Book of Oaths (qasamah), Retaliation and Blood Money",
    arabic: "كتاب القسامة",
    from: 4706,
    to: 4869,
  },
  {
    number: 47,
    english: "The Book of Cutting off the Hand of the Thief",
    arabic: "كتاب قطع السارق",
    from: 4870,
    to: 4984,
  },
  {
    number: 48,
    english: "The Book Of Faith and its Signs",
    arabic: "كتاب الإيمان وشرائعه",
    from: 4985,
    to: 5039,
  },
  {
    number: 49,
    english: "The Book of Adornment",
    arabic: "كتاب الزينة من السنن",
    from: 5040,
    to: 5378,
  },
  {
    number: 50,
    english: "The Book of the Etiquette of Judges",
    arabic: "كتاب آداب القضاة",
    from: 5379,
    to: 5427,
  },
  {
    number: 51,
    english: "The Book of Seeking Refuge with Allah",
    arabic: "كتاب الاستعاذة",
    from: 5428,
    to: 5539,
  },
  {
    number: 52,
    english: "The Book of Drinks",
    arabic: "كتاب الأشربة",
    from: 5540,
    to: 5758,
  },
];
