// tirmidhiChapters.js

export const tirmidhiChapters = [
  {
    number: 1,
    english: "The Book on Purification",
    arabic: "كتاب الطهارة عن رسول الله صلى الله عليه وسلم",
    from: 1,
    to: 148,
  },
  {
    number: 2,
    english: "The Book on Salat (Prayer)",
    arabic: "كتاب الصلاة",
    from: 149,
    to: 451,
  },
  {
    number: 3,
    english: "The Book on Al-Witr",
    arabic: "أَبْوَابُ الْوِتْرِ",
    from: 452,
    to: 487,
  },
  {
    number: 4,
    english: "The Book on the Day of Friday",
    arabic:
      "كِتَاب الْجُمُعَةِ عَنْ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ",
    from: 488,
    to: 529,
  },
  {
    number: 5,
    english: "The Book on the Two Eids",
    arabic:
      "أَبْوَابُ الْعِيدَيْنِ عَنْ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ",
    from: 530,
    to: 543,
  },
  {
    number: 6,
    english: "The Book on Traveling",
    arabic: "أَبْوَابُ السَّفَرِ",
    from: 544,
    to: 616,
  },
  {
    number: 7,
    english: "The Book on Zakat",
    arabic: "كتاب الزكاة عن رسول الله صلى الله عليه وسلم",
    from: 617,
    to: 681,
  },
  {
    number: 8,
    english: "The Book on Fasting",
    arabic: "كتاب الصوم عن رسول الله صلى الله عليه وسلم",
    from: 682,
    to: 808,
  },
  {
    number: 9,
    english: "The Book on Hajj",
    arabic: "كتاب الحج عن رسول الله صلى الله عليه وسلم",
    from: 809,
    to: 964,
  },
  {
    number: 10,
    english: "The Book on Jana''iz (Funerals)",
    arabic: "كتاب الجنائز عن رسول الله صلى الله عليه وسلم",
    from: 965,
    to: 1079,
  },
  {
    number: 11,
    english: "The Book on Marriage",
    arabic: "كتاب النكاح عن رسول الله صلى الله عليه وسلم",
    from: 1080,
    to: 1145,
  },
  {
    number: 12,
    english: "The Book on Suckling",
    arabic: "كتاب الرضاع",
    from: 1146,
    to: 1174,
  },
  {
    number: 13,
    english: "The Book on Divorce and Li'an",
    arabic: "كتاب الطلاق واللعان عن رسول الله صلى الله عليه وسلم",
    from: 1175,
    to: 1204,
  },
  {
    number: 14,
    english: "The Book on Business",
    arabic: "كتاب البيوع عن رسول الله صلى الله عليه وسلم",
    from: 1205,
    to: 1321,
  },
  {
    number: 15,
    english: "The Chapters On Judgements From The Messenger of Allah",
    arabic: "كتاب الأحكام عن رسول الله صلى الله عليه وسلم",
    from: 1322,
    to: 1385,
  },
  {
    number: 16,
    english: "The Book on Blood Money",
    arabic: "كتاب الديات عن رسول الله صلى الله عليه وسلم",
    from: 1386,
    to: 1422,
  },
  {
    number: 17,
    english: "The Book on Legal Punishments (Al-Hudud)",
    arabic: "كتاب الحدود عن رسول الله صلى الله عليه وسلم",
    from: 1423,
    to: 1463,
  },
  {
    number: 18,
    english: "The Book on Hunting",
    arabic: "كتاب الصيد والذبائح عن رسول الله صلى الله عليه وسلم",
    from: 1464,
    to: 1492,
  },
  {
    number: 19,
    english: "The Book on Sacrifices",
    arabic: "كتاب الأضاحى عن رسول الله صلى الله عليه وسلم",
    from: 1493,
    to: 1523,
  },
  {
    number: 20,
    english: "The Book on Vows and Oaths",
    arabic: "كتاب النذور والأيمان عن رسول الله صلى الله عليه وسلم",
    from: 1524,
    to: 1547,
  },
  {
    number: 21,
    english: "The Book on Military Expeditions",
    arabic: "كتاب السير عن رسول الله صلى الله عليه وسلم",
    from: 1548,
    to: 1618,
  },
  {
    number: 22,
    english: "The Book on Virtues of Jihad",
    arabic: "كتاب فضائل الجهاد عن رسول الله صلى الله عليه وسلم",
    from: 1619,
    to: 1669,
  },
  {
    number: 23,
    english: "The Book on Jihad",
    arabic: "كتاب الجهاد عن رسول الله صلى الله عليه وسلم",
    from: 1670,
    to: 1719,
  },
  {
    number: 24,
    english: "The Book on Clothing",
    arabic: "كتاب اللباس",
    from: 1720,
    to: 1787,
  },
  {
    number: 25,
    english: "The Book on Food",
    arabic: "كتاب الأطعمة عن رسول الله صلى الله عليه وسلم",
    from: 1788,
    to: 1860,
  },
  {
    number: 26,
    english: "The Book on Drinks",
    arabic: "كتاب الأشربة عن رسول الله صلى الله عليه وسلم",
    from: 1861,
    to: 1896,
  },
  {
    number: 27,
    english:
      "Chapters on Righteousness And Maintaining Good Relations With Relatives",
    arabic: "كتاب البر والصلة عن رسول الله صلى الله عليه وسلم",
    from: 1897,
    to: 2035,
  },
  {
    number: 28,
    english: "Chapters on Medicine",
    arabic: "كتاب الطب عن رسول اللَّهِ صلى الله عليه وسلم",
    from: 2036,
    to: 2088,
  },
  {
    number: 29,
    english: "Chapters On Inheritance",
    arabic: "كتاب الفرائض عن رسول الله صلى الله عليه وسلم",
    from: 2090,
    to: 2115,
  },
  {
    number: 30,
    english: "Chapters On Wasaya (Wills and Testament)",
    arabic: "كتاب الوصايا عن رسول الله صلى الله عليه وسلم",
    from: 2116,
    to: 2124,
  },
  {
    number: 31,
    english: "Chapters On Wala' And Gifts",
    arabic: "كتاب الولاء والهبة عن رسول الله صلى الله عليه وسلم",
    from: 2125,
    to: 2132,
  },
  {
    number: 32,
    english: "Chapters On Al-Qadar",
    arabic: "كتاب القدر عن رسول الله صلى الله عليه وسلم",
    from: 2133,
    to: 2157,
  },
  {
    number: 33,
    english: "Chapters On Al-Fitan",
    arabic: "كتاب الفتن عن رسول الله صلى الله عليه وسلم",
    from: 2158,
    to: 2269,
  },
  {
    number: 34,
    english: "Chapters On Dreams",
    arabic: "كتاب الرؤيا عن رسول الله صلى الله عليه وسلم",
    from: 2270,
    to: 2294,
  },
  {
    number: 35,
    english: "Chapters On Witnesses",
    arabic: "كتاب الشهادات عن رسول الله صلى الله عليه وسلم",
    from: 2295,
    to: 2303,
  },
  {
    number: 36,
    english: "Chapters On Zuhd",
    arabic: "كتاب الزهد عن رسول الله صلى الله عليه وسلم",
    from: 2304,
    to: 2414,
  },
  {
    number: 37,
    english:
      "Chapters on the description of the Day of Judgement, Ar-Riqaq, and Al-Wara'",
    arabic: "كتاب صفة القيامة والرقائق والورع عن رسول الله",
    from: 2415,
    to: 2522,
  },
  {
    number: 38,
    english: "Chapters on the description of Paradise",
    arabic: "كتاب صفة الجنة عن رسول الله صلى الله عليه وسلم",
    from: 2523,
    to: 2735,
  },
  {
    number: 39,
    english: "The Book on the Description of Hellfire",
    arabic: "كتاب صفة جهنم عن رسول الله صلى الله عليه وسلم",
    from: 2573,
    to: 2605,
  },
  {
    number: 40,
    english: "The Book on Faith",
    arabic: "كتاب الإيمان عن رسول الله صلى الله عليه وسلم",
    from: 2606,
    to: 2644,
  },
  {
    number: 41,
    english: "Chapters on Knowledge",
    arabic: "كتاب العلم عن رسول الله صلى الله عليه وسلم",
    from: 2645,
    to: 2687,
  },
  {
    number: 42,
    english: "Chapters on Seeking Permission",
    arabic: "كتاب الاستئذان والآداب عن رسول الله صلى الله عليه وسلم",
    from: 2688,
    to: 2735,
  },
  {
    number: 43,
    english: "Chapters on Manners",
    arabic: "كتاب الأدب عن رسول الله صلى الله عليه وسلم",
    from: 2736,
    to: 3093,
  },
  {
    number: 44,
    english: "Chapters on Parables",
    arabic: "كتاب الأمثال عن رسول الله صلى الله عليه وسلم",
    from: 2859,
    to: 2874,
  },
  {
    number: 45,
    english: "Chapters on The Virtues of the Qur'an",
    arabic: "كتاب ثواب القرآن عن رسول الله صلى الله عليه وسلم",
    from: 2875,
    to: 2926,
  },
  {
    number: 46,
    english: "Chapters on Recitation",
    arabic: "كتاب القراءات عن رسول الله صلى الله عليه وسلم",
    from: 2927,
    to: 2949,
  },
  {
    number: 47,
    english: "Chapters on Tafsir",
    arabic: "كتاب تفسير القرآن عن رسول الله صلى الله عليه وسلم",
    from: 2950,
    to: 3723,
  },
  {
    number: 48,
    english: "Chapters on Supplication",
    arabic: "كتاب الدعوات عن رسول الله صلى الله عليه وسلم",
    from: 3370,
    to: 3604,
  },
  {
    number: 49,
    english: "Chapters on Virtues",
    arabic: "كتاب المناقب عن رسول الله صلى الله عليه وسلم",
    from: 3605,
    to: 3956,
  },
];
