import { Platform, StyleSheet } from "react-native";
import { Z_INDEX } from "../constants/zIndex";

export const quranScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
    paddingTop: 60, // Ajout d'un padding en haut pour descendre le bouton
  },
  // 🎨 NOUVEAU : Styles pour le header avec menu
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    paddingHorizontal: 4,
  },
  headerInfo: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#523f13",
    fontFamily: "ScheherazadeNew",
  },
  headerSubtitle: {
    fontSize: 16,
    color: "#2c1810",
    fontFamily: "ScheherazadeNew",
    marginTop: 4,
    fontWeight: "500",
  },
  menuButton: {
    backgroundColor: "#e7c86a",
    borderRadius: 25,
    width: 50,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    borderColor: "#ba9c34",
    borderWidth: 2,
    boxShadow: "0px 2px 8px rgba(181,157,66,0.3)",
  },
  menuButtonText: {
    fontSize: 24,
    color: "#523f13",
    fontWeight: "bold",
  },
  menuOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  menuContent: {
    backgroundColor: "#fffbe6",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingBottom: 40,
    marginBottom: 10,
    maxHeight: "85%",
  },
  menuHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#e7c86a",
  },
  menuTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#523f13",
    fontFamily: "ScheherazadeNew",
  },
  menuSection: {
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  menuSectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#ba9c34",
    marginBottom: 12,
    fontFamily: "ScheherazadeNew",
  },
  menuOption: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#f8f8f8",
    padding: 16,
    borderRadius: 12,
    borderColor: "#e7c86a",
    borderWidth: 1,
  },
  menuOptionText: {
    fontSize: 16,
    color: "#523f13",
    fontFamily: "ScheherazadeNew",
    flex: 1,
  },
  menuOptionSubtitle: {
    fontSize: 12,
    color: "#8b7355",
    fontStyle: "italic",
    marginTop: 2,
  },
  checkMark: {
    fontSize: 18,
    color: "#4CAF50",
    fontWeight: "bold",
    marginLeft: 10,
  },
  menuArrow: {
    fontSize: 20,
    color: "#ba9c34",
    marginLeft: 10,
  },
  // 🎨 ANCIEN : Styles pour le header compact (gardé pour la version offline)
  compactHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(231, 200, 106, 0.15)",
    borderRadius: 16,
    padding: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#e7c86a",
    gap: 8,
  },
  compactSourateSelector: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fffbe6",
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "#ba9c34",
    flex: 2,
  },
  compactLangSelector: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fffbe6",
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "#ba9c34",
    flex: 1,
  },
  compactSourateText: {
    fontSize: 14,
    color: "#2c1810",
    fontWeight: "600",
    flex: 1,
    marginRight: 8,
  },
  compactLangText: {
    fontSize: 14,
    color: "#2c1810",
    fontWeight: "600",
    marginRight: 8,
  },
  versesContainer: {
    paddingBottom: 20,
    marginRight: 4,
  },
  compactReciterSelector: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fffbe6",
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "#ba9c34",
    flex: 1.5,
  },
  compactReciterText: {
    flex: 1,
    fontSize: 12,
    color: "#483C1C",
    fontWeight: "500",
    marginHorizontal: 4,
  },
  // ðŸŒ NOUVEAU : Section des contrÃ´les hors ligne
  offlineControlsSection: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 12,
    paddingHorizontal: 16,
  },
  // ðŸŒ NOUVEAU : Styles pour les indicateurs de connectivitÃ©
  offlineIndicator: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff5f5",
    borderRadius: 8,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: "#ff6b6b",
  },
  offlineText: {
    fontSize: 11,
    color: "#d63031",
    fontWeight: "500",
    marginLeft: 4,
  },
  connectivityIndicator: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fffbe6",
    borderRadius: 8,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: "#ba9c34",
  },
  connectivityText: {
    fontSize: 11,
    color: "#ba9c34",
    fontWeight: "500",
    marginLeft: 4,
  },
  diagnosticButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ff6b6b",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    marginLeft: 8,
  },
  diagnosticButtonText: {
    fontSize: 12,
    color: "#ffffff",
    marginLeft: 4,
    fontWeight: "bold",
  },
  // ðŸŒ NOUVEAU : Styles pour le bouton de basculement mode hors ligne
  offlineManagerButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fffbe6",
    borderRadius: 8,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: "#ba9c34",
  },
  offlineManagerButtonActive: {
    backgroundColor: "#fff5f5",
    borderColor: "#ff6b6b",
  },
  offlineManagerButtonText: {
    fontSize: 11,
    color: "#ba9c34",
    fontWeight: "500",
    marginLeft: 4,
  },
  offlineManagerButtonTextActive: {
    color: "#d63031",
  },
  // ðŸŒ NOUVEAU : Styles pour la liste des rÃ©citations hors ligne
  offlineRecitationsContainer: {
    flex: 1,
    paddingHorizontal: 16,
  },
  offlineRecitationsTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#483C1C",
    textAlign: "center",
    marginBottom: 20,
    fontFamily: "ScheherazadeNew",
  },
  // 🎵 NOUVEAU : Styles pour la navigation par récitateur
  offlineHeader: {
    marginBottom: 16,
  },
  offlineHeaderWithBack: {
    flexDirection: "column",
    gap: 8,
  },
  backButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    alignSelf: "flex-start",
    padding: 8,
    borderRadius: 8,
    backgroundColor: "rgba(231, 200, 106, 0.1)",
  },
  backButtonText: {
    fontSize: 14,
    color: "#ba9c34",
    fontWeight: "600",
  },
  offlineReciterItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(231, 200, 106, 0.1)",
    borderRadius: 12,
    padding: 16,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#e7c86a",
  },
  offlineReciterInfo: {
    flex: 1,
  },
  offlineReciterHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 4,
  },
  offlineReciterName: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#483C1C",
    flex: 1,
  },
  offlineReciterCount: {
    fontSize: 14,
    color: "#ba9c34",
    fontWeight: "500",
  },
  offlineRecitersList: {
    paddingBottom: 120, // Espace pour le menu de navigation en bas
  },
  // 🎵 NOUVEAU : Styles pour la playlist et lecture en continu
  offlineReciterTitleContainer: {
    flexDirection: "column",
    alignItems: "center",
    flex: 1,
  },
  playlistIndicator: {
    fontSize: 12,
    color: "#4ECDC4",
    fontWeight: "600",
    marginTop: 4,
  },
  playlistControls: {
    marginTop: 12,
  },
  playAllButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 12,
    borderRadius: 8,
    backgroundColor: "rgba(78, 205, 196, 0.1)",
    borderWidth: 1,
    borderColor: "#4ECDC4",
  },
  playAllButtonText: {
    fontSize: 14,
    color: "#4ECDC4",
    fontWeight: "600",
  },
  stopPlaylistButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 12,
    borderRadius: 8,
    backgroundColor: "rgba(255, 107, 107, 0.1)",
    borderWidth: 1,
    borderColor: "#FF6B6B",
  },
  stopPlaylistButtonText: {
    fontSize: 14,
    color: "#FF6B6B",
    fontWeight: "600",
  },
  offlineRecitationItemActive: {
    backgroundColor: "rgba(78, 205, 196, 0.05)",
    borderColor: "#4ECDC4",
    borderWidth: 2,
  },
  offlineRecitationTitleContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  playlistCurrentIcon: {
    marginRight: 8,
  },
  offlineRecitationTitleActive: {
    color: "#4ECDC4",
    fontWeight: "bold",
  },
  offlineRecitationBadgesContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  playlistPositionBadge: {
    backgroundColor: "rgba(78, 205, 196, 0.1)",
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  playlistPositionText: {
    fontSize: 10,
    color: "#4ECDC4",
    fontWeight: "600",
  },
  noRecitationsContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 40,
  },
  noRecitationsTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#ba9c34",
    textAlign: "center",
    marginTop: 16,
    marginBottom: 8,
  },
  noRecitationsSubtitle: {
    fontSize: 14,
    color: "#666",
    textAlign: "center",
    paddingHorizontal: 20,
    lineHeight: 20,
  },
  offlineRecitationsList: {
    paddingBottom: 120, // Espace pour le menu de navigation en bas
  },
  offlineRecitationItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fffbe6",
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#e7c86a",
    boxShadow: "0px 2px 4px rgba(0,0,0,0.1)",
  },
  offlineRecitationInfo: {
    flex: 1,
    marginRight: 12,
  },
  offlineRecitationTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#483C1C",
    marginBottom: 4,
  },
  offlineRecitationSubtitle: {
    fontSize: 13,
    color: "#ba9c34",
    opacity: 0.8,
  },
  offlineRecitationReciter: {
    fontSize: 14,
    color: "#ba9c34",
    marginBottom: 6,
  },
  offlineRecitationBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#e8f5e8",
    borderRadius: 8,
    paddingVertical: 2,
    paddingHorizontal: 6,
    alignSelf: "flex-start",
  },
  offlineRecitationBadgeText: {
    fontSize: 10,
    color: "#4CAF50",
    fontWeight: "500",
    marginLeft: 2,
  },
  offlineRecitationActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  offlineRecitationPlayButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(78, 205, 196, 0.2)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#4ECDC4",
  },
  offlineRecitationPlayButtonActive: {
    backgroundColor: "rgba(255, 107, 107, 0.2)",
    borderColor: "#FF6B6B",
  },
  offlineRecitationDeleteButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255, 107, 107, 0.1)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#FF6B6B",
  },
  // 🚀 SUPPRIMÉ : Styles du bouton de rechargement (plus nécessaire)
  // 🎨 NOUVEAU : Bouton play flottant pour les récitations premium
  floatingPlayButton: {
    position: "absolute",
    bottom: 140, // Augmenté davantage pour être complètement visible
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#4ECDC4",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0px 2px 4px rgba(0,0,0,0.25)",
    zIndex: Z_INDEX.modal,
  },
  floatingPlayButtonInactive: {
    backgroundColor: "#ba9c34",
  },
  // 🎨 NOUVEAU : Styles pour le modal des contrôles audio
  audioModalContainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  audioModalScrollView: {
    flex: 1,
    width: "100%",
  },
  audioModalScrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  audioModalContent: {
    backgroundColor: "transparent", // Transparent pour voir le GIF
    borderRadius: 20,
    paddingBottom: 20, // Padding en bas pour l'espace
    width: "90%",
    maxWidth: 400,
  },
  audioModalOverlay: {
    backgroundColor: "transparent", // Transparent pour voir le GIF
    borderRadius: 20,
    paddingBottom: 20, // Padding en bas
  },
  audioModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    // padding: 16, // SUPPRIMÉ
    // borderBottomWidth: 1, // SUPPRIMÉ
    // borderBottomColor: "#e7c86a", // SUPPRIMÉ
  },
  // 🎵 NOUVEAU : Bouton de sélection de GIF (premium)
  gifSelectorButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
  },
  audioModalTitle: {
    fontSize: 18,
    color: "#FFF",
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 4,
    textShadowColor: "rgba(0,0,0,0.7)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  audioModalSubtitle: {
    fontSize: 14,
    color: "#FFF",
    fontWeight: "600",
    textAlign: "center",
    marginBottom: 8,
    textShadowColor: "rgba(0,0,0,0.7)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  audioModalBody: {
    alignSelf: "stretch",
    alignItems: "center",
    width: "100%",
    paddingHorizontal: 12,
  },
  // 🎵 NOUVEAU : Styles pour l'indicateur de lecture (GIF maintenant en fond)
  audioAnimationContainer: {
    alignSelf: "stretch",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
    marginHorizontal: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: "rgba(78, 205, 196, 0.2)",
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "rgba(78, 205, 196, 0.6)",
    minHeight: 44,
  },

  // 🎵 NOUVEAU : Styles pour la barre de progression améliorée
  seekBarContainer: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    height: 32,
    gap: 8,
  },

  seekBarTimeSlot: {
    width: 52,
    height: 32,
    justifyContent: "center",
    alignItems: "center",
  },

  seekBarWrapper: {
    flex: 1,
    height: 32,
    justifyContent: "center",
    position: "relative",
  },

  audioProgressBarActive: {
    height: 10,
    borderWidth: 1,
    borderColor: "#FF6B6B",
    borderRadius: 5,
  },

  audioTimeTextActive: {
    color: "#FF6B6B",
  },

  seekPreview: {
    position: "absolute",
    top: -40, // Ajusté pour le curseur de taille normale
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    transform: [{ translateX: -20 }], // Centrage pour curseur 16px
    boxShadow: "0px 2px 4px rgba(0,0,0,0.3)",
  },

  seekPreviewText: {
    color: "#FFF",
    fontSize: 14, // Plus gros pour une meilleure lisibilité
    fontWeight: "700", // Plus gras
    textAlign: "center",
  },

  audioAnimationText: {
    fontSize: 16,
    color: "#4ECDC4",
    fontWeight: "700",
    fontStyle: "italic",
    textAlign: "center",
    width: "100%",
    flexShrink: 1,
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  debugText: {
    fontSize: 10,
    color: "#FF6B6B",
    fontWeight: "400",
    fontStyle: "italic",
    marginTop: 5,
  },
  debugBackgroundColor: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(255, 0, 255, 0.2)", // Magenta pour debug
    borderRadius: 20,
    zIndex: -1,
  },
  audioModalGifOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 20,
    width: "100%",
    height: "100%",
    opacity: 0.6,
    zIndex: 1,
  },
  audioModalGifBackground: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 20,
    width: "100%",
    height: "100%",
    opacity: 1, // GIF complètement visible
    zIndex: 0,
    backgroundColor: "transparent",
  },
  audioInfoContainer: {
    alignItems: "center",
    marginBottom: 20,
    padding: 15,
    backgroundColor: "rgba(231, 200, 106, 0.1)",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e7c86a",
    width: "100%",
  },
  audioReciterName: {
    fontSize: 17,
    fontWeight: "bold",
    color: "#FFF",
    textAlign: "center",
    marginBottom: 2,
    textShadowColor: "rgba(0,0,0,0.85)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  audioSurahName: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#FFF",
    textAlign: "center",
    marginBottom: 10,
    textShadowColor: "rgba(0,0,0,0.85)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  audioLocalBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(76, 175, 80, 0.1)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#4CAF50",
  },
  audioLocalText: {
    fontSize: 12,
    color: "#4CAF50",
    fontWeight: "600",
    marginLeft: 4,
  },
  audioMainControls: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    paddingHorizontal: 20,
    marginBottom: 24,
    gap: 20,
    zIndex: 10,
  },
  audioSecondaryControlButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "rgba(255, 255, 255, 0.3)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.5)",
    boxShadow: "0px 2px 3px rgba(0,0,0,0.2)",
  },
  audioPlayButton: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#4ECDC4",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0px 2px 4px rgba(0,0,0,0.25)",
  },
  audioPlayButtonActive: {
    backgroundColor: "#FF6B6B",
  },
  audioProgressContainer: {
    width: "100%",
    marginBottom: 20,
  },
  audioTimeText: {
    fontSize: 14,
    color: "#666",
    fontWeight: "600",
    width: 52,
    textAlign: "center",
    lineHeight: 18,
    ...(Platform.OS === "android" ? { includeFontPadding: false } : {}),
    fontVariant: ["tabular-nums"],
  },
  audioProgressBarTouchTarget: {
    width: "100%",
    height: 32,
    justifyContent: "center",
  },
  audioProgressBar: {
    flexDirection: "row",
    width: "100%",
    height: 8,
    backgroundColor: "rgba(186, 156, 52, 0.3)",
    borderRadius: 4,
    overflow: "hidden",
  },
  audioProgressFill: {
    height: 8,
    borderRadius: 4,
  },
  audioDownloadButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.15)",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.3)",
    marginBottom: 12,
    boxShadow: "0px 2px 4px rgba(0,0,0,0.1)",
  },
  audioDownloadText: {
    fontSize: 16,
    color: "#222",
    fontWeight: "600",
    marginLeft: 8,
    textShadowColor: "rgba(0,0,0,0.7)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  audioStopButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.15)",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.3)",
    boxShadow: "0px 2px 4px rgba(0,0,0,0.1)",
  },
  audioStopText: {
    fontSize: 16,
    color: "#222",
    fontWeight: "600",
    marginLeft: 8,
    textShadowColor: "rgba(0,0,0,0.7)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  audioOptionsContainer: {
    marginBottom: 12,
  },
  downloadedInfoContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(76, 175, 80, 0.1)",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: "#4CAF50",
  },
  downloadedInfoText: {
    flex: 1,
    fontSize: 16,
    color: "#4CAF50",
    fontWeight: "600",
    marginLeft: 8,
  },
  audioDeleteButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: "rgba(255, 107, 107, 0.1)",
    borderWidth: 1,
    borderColor: "#FF6B6B",
  },
  // 🎯 NOUVEAU : Styles pour la navigation entre sourates (COMPACT)
  audioNavigationContainer: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.25)",
    marginTop: 4,
    marginBottom: 8,
    boxShadow: "0px 1px 3px rgba(0,0,0,0.08)",
  },
  audioNavButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 6,
    backgroundColor: "rgba(255,255,255,0.15)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.3)",
    minWidth: 60,
    justifyContent: "center",
    boxShadow: "0px 1px 2px rgba(0,0,0,0.06)",
  },
  audioNavButtonDisabled: {
    backgroundColor: "rgba(200,200,200,0.5)",
    borderColor: "#bbb",
  },
  audioNavButtonText: {
    fontSize: 12,
    color: "#222",
    fontWeight: "600",
    marginHorizontal: 2,
    textShadowColor: "rgba(0,0,0,0.7)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  // 🎯 NOUVEAU : Styles pour l'info navigation
  navigationInfoContainer: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    paddingVertical: 8,
    paddingHorizontal: 20,
    marginTop: 8,
    position: "relative",
  },
  navigationInfoButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  navigationInfoText: {
    color: "#B0B0B0",
    fontSize: 12,
    marginLeft: 4,
    fontWeight: "600",
  },
  navigationInfoTextActive: {
    color: "#4ECDC4",
  },
  // Styles de la Modal d'information de navigation
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  modalNavigationTooltip: {
    backgroundColor: "rgba(20, 20, 20, 0.95)",
    borderRadius: 16,
    padding: 24,
    width: "90%",
    maxWidth: 350,
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.2)",
    boxShadow: "0px 10px 15px rgba(0,0,0,0.5)",
  },
  modalNavigationTooltipTitle: {
    color: "#FFD700",
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 20,
  },
  modalNavigationTooltipRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    paddingHorizontal: 8,
  },
  modalNavigationTooltipText: {
    color: "#FFFFFF",
    fontSize: 15,
    marginLeft: 12,
    flex: 1,
    lineHeight: 20,
  },
  modalCloseButton: {
    backgroundColor: "#4ECDC4",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 24,
    alignSelf: "center",
    marginTop: 8,
  },
  modalCloseButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
  audioCurrentSurah: {
    alignItems: "center",
    marginBottom: 4,
  },
  audioCurrentSurahText: {
    fontSize: 14,
    color: "#FFF",
    fontWeight: "bold",
    textShadowColor: "rgba(0,0,0,0.7)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  audioCurrentSurahName: {
    fontSize: 12,
    color: "#FFF",
    fontStyle: "italic",
    textShadowColor: "rgba(0,0,0,0.7)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  audioNavButtonsContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    marginTop: 4,
  },
  // 🎯 NOUVEAU : Styles pour le contrôle du scroll automatique
  autoScrollContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(186, 156, 52, 0.1)",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: "#ba9c34",
    marginBottom: 12,
  },
  autoScrollLeft: {
    flex: 1,
  },
  confidenceText: {
    fontSize: 12,
    color: "#666",
    fontStyle: "italic",
    marginTop: 2,
  },
  autoScrollText: {
    fontSize: 16,
    color: "#483C1C",
    fontWeight: "600",
  },
  autoScrollToggle: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: "rgba(186, 156, 52, 0.2)",
    borderWidth: 1,
    borderColor: "#ba9c34",
  },
  autoScrollToggleActive: {
    backgroundColor: "rgba(78, 205, 196, 0.2)",
    borderColor: "#4ECDC4",
  },
  selectStyle: {
    backgroundColor: "#e7c86a",
    borderRadius: 22,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderColor: "#ba9c34",
    borderWidth: 2,
    boxShadow: "0px 2px 8px rgba(181,157,66,0.3)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 18,
  },
  selectTextStyle: {
    fontSize: 18,
    color: "#483C1C",
    fontFamily: "ScheherazadeNew",
    textAlign: "left",
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContent: {
    backgroundColor: "#fffbe6",
    borderRadius: 20,
    width: "90%",
    boxShadow: "0px 2px 4px rgba(0,0,0,0.25)",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#e7c86a",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#483C1C",
  },
  closeButton: {
    padding: 8,
  },
  closeButtonText: {
    fontSize: 20,
    color: "#483C1C",
  },
  // 🎵 NOUVEAU : Styles pour la liste de sélection de GIF
  gifList: {
    maxHeight: 400,
  },
  gifOption: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 15,
    marginBottom: 12,
    marginHorizontal: 16,
    borderWidth: 2,
    borderColor: "transparent",
    boxShadow: "0px 1px 2px rgba(0,0,0,0.2)",
  },
  selectedGifOption: {
    borderColor: "#4CAF50",
    backgroundColor: "#f0f8f0",
  },
  lockedGifOption: {
    opacity: 0.6,
  },
  gifPreview: {
    width: 60,
    height: 60,
    borderRadius: 8,
    marginRight: 12,
  },
  gifInfo: {
    flex: 1,
  },
  gifName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#242428",
    marginBottom: 4,
  },
  selectedGifName: {
    color: "#4CAF50",
  },
  premiumBadge: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 4,
  },
  premiumText: {
    fontSize: 12,
    color: "#FFD700",
    marginLeft: 4,
    fontWeight: "600",
  },
  listContent: {
    paddingBottom: 20,
  },
  optionStyle: {
    backgroundColor: "#fffbe6",
    borderBottomWidth: 1,
    borderColor: "#e7c86a",
    padding: 12,
  },
  selectedOptionStyle: {
    backgroundColor: "#e7c86a",
  },
  optionTextStyle: {
    fontSize: 18,
    color: "#444",
    fontFamily: "ScheherazadeNew",
  },
  selectedOptionTextStyle: {
    color: "#483C1C",
    fontWeight: "bold",
  },
  ayahContainer: {
    marginVertical: 12,
    paddingVertical: 8,
  },
  // 🎯 NOUVEAU : Styles pour le verset en cours de lecture
  ayahContainerPlaying: {
    backgroundColor: "rgba(78, 205, 196, 0.1)",
    borderRadius: 12,
    paddingHorizontal: 12,
    borderWidth: 2,
    borderColor: "#4ECDC4",
    boxShadow: "0px 1px 4px rgba(78,205,196,0.3)",
  },
  arabicPlaying: {
    color: "#2E8B57",
    fontWeight: "bold",
  },
  verseCirclePlaying: {
    backgroundColor: "#4ECDC4",
    borderColor: "#2E8B57",
    boxShadow: "0px 0px 3px rgba(78,205,196,0.5)",
  },
  verseNumberPlaying: {
    color: "#fff",
    fontWeight: "bold",
  },
  arabic: {
    fontSize: 30,
    textAlign: "right",
    color: "#222",
    marginBottom: 8,
    fontFamily: "ScheherazadeNew",
    lineHeight: 60,
    flex: 1,
    flexShrink: 1,
  },
  phonetic: {
    fontSize: 16,
    fontStyle: "italic",
    color: "#666",
    marginBottom: 2,
  },
  traduction: {
    fontSize: 16,
    textAlign: "left",
    color: "#338",
    marginBottom: 2,
  },
  ayahSeparator: {
    marginTop: 50,
    alignSelf: "center",
    width: 50,
    height: 50,
    marginVertical: 7,
  },
  bismillah: {
    textAlign: "center",
    color: "#7c6720",
    fontSize: 28,
    marginVertical: 12,
    fontFamily: "ScheherazadeNew",
    lineHeight: 44,
    letterSpacing: 1,
  },
  arabicRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  verseCircle: {
    backgroundColor: "#e7c86a",
    borderRadius: 14,
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
    borderWidth: 1,
    borderColor: "#ba9c34",
    boxShadow: "0px 1px 2px rgba(160,128,42,0.12)",
  },
  verseNumber: {
    color: "#6b510e",
    fontWeight: "bold",
    fontSize: 15,
    fontFamily: "ScheherazadeNew",
  },
  verseActions: {
    flexDirection: "column",
    alignItems: "center",
    gap: 6,
    marginLeft: 8,
  },
  favoriteButtonCompact: {
    padding: 4,
    borderRadius: 8,
    backgroundColor: "rgba(186, 156, 52, 0.08)",
  },
  searchInput: {
    height: 40,
    backgroundColor: "#fffbe6",
    borderRadius: 20,
    borderColor: "#ba9c34",
    borderWidth: 1.5,
    paddingHorizontal: 20,
    paddingVertical: 10,
    fontSize: 14,
    color: "#523f13",
    textAlign: "left",
  },
  sourateHeader: {
    backgroundColor: "rgba(231, 200, 106, 0.2)",
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginBottom: 12,
    borderLeftWidth: 4,
    borderLeftColor: "#e7c86a",
  },
  sourateName: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#7c6720",
    textAlign: "center",
    fontFamily: "ScheherazadeNew",
  },
  searchContainer: {
    marginBottom: 10,
    paddingHorizontal: 15,
  },
  searchLoader: {
    position: "absolute",
    right: 15,
    top: "50%",
    marginTop: -10,
  },
  searchInfo: {
    fontSize: 14,
    color: "#7c6720",
    textAlign: "center",
    marginBottom: 12,
    fontStyle: "italic",
  },

  // Styles pour la section récitateur premium rétractable
  reciterSection: {
    backgroundColor: "rgba(231, 200, 106, 0.15)",
    borderRadius: 16,
    padding: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#e7c86a",
  },
  reciterHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#fffbe6",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: "#ba9c34",
  },
  reciterHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  reciterHeaderText: {
    flex: 1,
    marginLeft: 12,
    marginRight: 12,
    fontSize: 16,
    color: "#483C1C",
    fontWeight: "500",
  },
  reciterHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  reciterSelectorButton: {
    padding: 4,
    borderRadius: 8,
    backgroundColor: "rgba(186, 156, 52, 0.1)",
  },
  collapseButton: {
    padding: 4,
    borderRadius: 8,
    backgroundColor: "rgba(186, 156, 52, 0.1)",
  },
  // 🎨 NOUVEAU : Styles pour les contrôles compacts
  compactControls: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  compactPlayButton: {
    padding: 12,
    borderRadius: 25,
    backgroundColor: "rgba(78, 205, 196, 0.2)",
    borderWidth: 1,
    borderColor: "#4ECDC4",
    alignItems: "center",
    justifyContent: "center",
  },
  activeCompactButton: {
    backgroundColor: "rgba(78, 205, 196, 0.4)",
  },
  // Anciens styles conservés pour compatibilité
  reciterSelector: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#fffbe6",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: "#ba9c34",
  },
  reciterText: {
    flex: 1,
    marginLeft: 12,
    marginRight: 12,
    fontSize: 16,
    color: "#483C1C",
    fontWeight: "500",
  },
  audioControls: {
    marginTop: 12,
    alignItems: "center",
  },
  noRecitationText: {
    fontSize: 14,
    color: "#7c6720",
    fontStyle: "italic",
    textAlign: "center",
    padding: 8,
  },
  downloadProgress: {
    width: "100%",
    alignItems: "center",
  },
  downloadHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  downloadProgressTitle: {
    fontSize: 14,
    color: "#7c6720",
    fontWeight: "600",
  },
  cancelButton: {
    padding: 6,
    borderRadius: 20,
    backgroundColor: "rgba(255, 107, 107, 0.2)",
    borderWidth: 1,
    borderColor: "#FF6B6B",
  },
  progressBar: {
    width: "100%",
    height: 8,
    backgroundColor: "rgba(186, 156, 52, 0.2)",
    borderRadius: 4,
    overflow: "hidden",
    marginBottom: 8,
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#4ECDC4",
    borderRadius: 4,
  },
  progressText: {
    fontSize: 12,
    color: "#7c6720",
    fontWeight: "bold",
  },
  downloadButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(78, 205, 196, 0.1)",
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: "#4ECDC4",
  },
  downloadButtonText: {
    fontSize: 14,
    color: "#FFD700",
    fontWeight: "600",
  },
  downloadWarningText: {
    fontSize: 11,
    color: "#7c6720",
    fontStyle: "italic",
    marginTop: 2,
    textAlign: "center",
  },
  bandwidthInfo: {
    fontSize: 12,
    color: "#7c6720",
    fontStyle: "italic",
    textAlign: "center",
    marginTop: 8,
    opacity: 0.8,
  },
  playbackControls: {
    marginTop: 12,
    gap: 8,
  },
  progressContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  timeText: {
    fontSize: 12,
    color: "#666",
    fontWeight: "600",
    minWidth: 40,
    textAlign: "center",
  },
  progressBarContainer: {
    flex: 1,
    height: 30,
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  progressBarAudio: {
    height: 6,
    backgroundColor: "rgba(186, 156, 52, 0.3)",
    borderRadius: 3,
    overflow: "hidden",
  },
  progressFillAudio: {
    height: "100%",
    backgroundColor: "#4ECDC4",
    borderRadius: 3,
  },
  controlButtons: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
  },
  controlButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: "rgba(231, 200, 106, 0.2)",
    borderWidth: 1,
    borderColor: "#e7c86a",
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },

  // Nouveaux styles pour la nouvelle structure de contrôles audio
  loadingContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: 16,
  },
  loadingText: {
    fontSize: 14,
    color: "#7c6720",
    fontWeight: "600",
  },
  recitationOptions: {
    backgroundColor: "rgba(231, 200, 106, 0.1)",
    borderRadius: 12,
    padding: 16,
    margin: 8,
    borderWidth: 1,
    borderColor: "#e7c86a",
  },
  recitationTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#483C1C",
    textAlign: "center",
    marginBottom: 12,
  },
  recitationActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    marginBottom: 8,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    padding: 10,
    borderRadius: 8,
    backgroundColor: "rgba(231, 200, 106, 0.2)",
    borderWidth: 1,
    borderColor: "#e7c86a",
  },
  streamButton: {
    backgroundColor: "rgba(78, 205, 196, 0.2)",
    borderColor: "#4ECDC4",
  },
  activeButton: {
    backgroundColor: "rgba(78, 205, 196, 0.4)",
  },
  streamButtonText: {
    fontSize: 14,
    color: "#4ECDC4",
    fontWeight: "600",
  },
  downloadedIndicator: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    padding: 8,
    borderRadius: 8,
    backgroundColor: "rgba(76, 175, 80, 0.1)",
    borderWidth: 1,
    borderColor: "#4CAF50",
  },
  downloadedText: {
    fontSize: 12,
    color: "#4CAF50",
    fontWeight: "600",
  },
  downloadedSection: {
    backgroundColor: "rgba(231, 200, 106, 0.1)",
    borderRadius: 12,
    padding: 16,
    margin: 8,
    borderWidth: 1,
    borderColor: "#e7c86a",
  },
  downloadedHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  deleteButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: "rgba(231, 200, 106, 0.2)",
    borderWidth: 1,
    borderColor: "#e7c86a",
  },
  mainControls: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
  },
  mainPlayButton: {
    padding: 10,
    borderRadius: 8,
    backgroundColor: "rgba(78, 205, 196, 0.2)",
    borderWidth: 1,
    borderColor: "#4ECDC4",
  },
  activePlayButton: {
    backgroundColor: "rgba(78, 205, 196, 0.4)",
  },
  stopButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: "rgba(231, 200, 106, 0.2)",
    borderWidth: 1,
    borderColor: "#e7c86a",
  },
  clearQuranButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 107, 107, 0.1)",
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "#FF6B6B",
    gap: 4,
  },
  clearQuranButtonText: {
    fontSize: 12,
    color: "#FF6B6B",
    fontWeight: "600",
  },
  stopButtonCenter: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: "rgba(255, 107, 107, 0.2)",
    borderWidth: 1,
    borderColor: "#FF6B6B",
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },

  // 🚀 NOUVEAU : Styles pour la jauge de progression
  downloadProgressContainer: {
    backgroundColor: "rgba(231, 200, 106, 0.1)",
    borderRadius: 12,
    padding: 12,
    marginVertical: 8,
    borderWidth: 1,
    borderColor: "#e7c86a",
  },
  downloadProgressHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  downloadProgressCancelButton: {
    padding: 6,
    borderRadius: 20,
    backgroundColor: "rgba(255, 107, 107, 0.2)",
    borderWidth: 1,
    borderColor: "#FF6B6B",
    alignItems: "center",
    justifyContent: "center",
  },
  downloadProgressBackground: {
    height: 8,
    backgroundColor: "rgba(186, 156, 52, 0.3)",
    borderRadius: 4,
    overflow: "hidden",
  },
  downloadProgressFill: {
    height: "100%",
    backgroundColor: "#4ECDC4",
    borderRadius: 4,
  },
  // Titre principal adapté (nom du récitateur et de la sourate)
  audioReciterSurahTitle: {
    fontSize: 16,
    color: "#FFF",
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 10,
    textShadowColor: "rgba(0,0,0,0.7)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  // 📱 NOUVEAU : Styles pour la page offline
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#2c1810",
    marginBottom: 16,
    textAlign: "center",
  },
  placeholderText: {
    fontSize: 14,
    color: "#666",
    textAlign: "center",
    fontStyle: "italic",
    lineHeight: 20,
  },
  compactHeaderOffline: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(231, 200, 106, 0.15)",
    borderRadius: 12, // ✅ RÉDUIT de 16 à 12
    padding: 8, // ✅ RÉDUIT de 12 à 8
    marginBottom: 8, // ✅ RÉDUIT de 16 à 8
    borderWidth: 1,
    borderColor: "#e7c86a",
    gap: 6, // ✅ RÉDUIT de 8 à 6
  },
});
