name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm test -- --coverage --passWithNoTests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run security audit
        run: npm audit --audit-level=moderate

      - name: Check for secrets in code
        run: |
          echo "🔍 Scanning for potential secrets..."
          # Use the same improved scan as security.yml
          SCAN_RESULTS=$(grep -r -i "password\|secret\|key\|token\|api_key" . \
            --exclude-dir=node_modules \
            --exclude-dir=.git \
            --exclude-dir=__tests__ \
            --exclude-dir=coverage \
            --exclude-dir=locales \
            --exclude="*.md" \
            --exclude="*.test.ts" \
            --exclude="*.test.tsx" \
            --exclude="*locales*.json" \
            --exclude="*template*.php" \
            --exclude="*config-template*" \
            | grep -v "test-" \
            | grep -v "mock" \
            | grep -v "verse_key" \
            | grep -v "method_Turkey" \
            | grep -v "Turkey" \
            | grep -v "jest.fn" \
            | grep -v "jest.fn((key)" \
            | grep -v "translation.*key" \
            | grep -v '"key"' \
            | grep -v "'key'" \
            | grep -v "keyof" \
            | grep -v "apiKey.*test" \
            | grep -v "password_hash" \
            | grep -v "password_verify" \
            | grep -v "PASSWORD_DEFAULT" \
            | grep -v "validation_password" \
            | grep -v "help_password" \
            | grep -v "AdhanSoundKey" \
            | grep -v "CalcMethodKey" \
            | grep -v "STORAGE_KEY" \
            | grep -v "keysToPreserve" \
            | grep -v "keysToDelete" \
            | grep -v "error_log.*password" || true)
          
          if [ -n "$SCAN_RESULTS" ]; then
            echo "❌ Real secrets found in code:"
            echo "================================"
            echo "$SCAN_RESULTS"
            echo "================================"
            echo "Please remove or move these secrets to environment variables"
            exit 1
          else
            echo "✅ No real secrets found"
          fi

  build:
    needs: [test, security]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build Android
        run: eas build --platform android --non-interactive

      - name: Build iOS
        run: eas build --platform ios --non-interactive

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        run: |
          echo "🚀 Deploying to production server..."
          # Add your deployment script here
          # Example: ./scripts/deploy.sh
